-- Aldren's Grandmaster Workshop
-- Static knowledge archives extracted in version 1.3.2.
-- No player-facing behavior lives in this file.

AAW = AAW or {}

-- Static reagent trait map.
-- We use this because the game can tell us whether a trait slot is known,
-- but hidden trait names are not always shown until the player discovers them.
AAW.reagentTraits = {
    ["beetle scuttle"] = { "Breach", "Increase Armor", "Protection", "Vitality" },
    ["blessed thistle"] = { "Ravage Health", "Restore Stamina", "Increase Weapon Power", "Speed" },
    ["blue entoloma"] = { "Restore Health", "Ravage Magicka", "Cowardice", "Invisible" },
    ["bugloss"] = { "Restore Health", "Restore Magicka", "Increase Spell Resist", "Cowardice" },
    ["butterfly wing"] = { "Restore Health", "Uncertainty", "Lingering Health", "Vitality" },
    ["chaurus egg"] = { "Ravage Magicka", "Restore Stamina", "Detection", "Timidity" },
    ["clam gall"] = { "Increase Spell Resist", "Hindrance", "Vulnerability", "Defile" },
    ["columbine"] = { "Restore Health", "Restore Magicka", "Restore Stamina", "Unstoppable" },
    ["corn flower"] = { "Ravage Health", "Restore Magicka", "Increase Spell Power", "Detection" },
    ["crimson nirnroot"] = { "Restore Health", "Spell Critical", "Gradual Ravage Health", "Timidity" },
    ["dragon rheum"] = { "Restore Magicka", "Enervation", "Speed", "Heroism" },
    ["dragon's bile"] = { "Invisible", "Vulnerability", "Vitality", "Heroism" },
    ["dragon's blood"] = { "Restore Stamina", "Lingering Health", "Defile", "Heroism" },
    ["dragonthorn"] = { "Restore Stamina", "Fracture", "Increase Weapon Power", "Weapon Critical" },
    ["emetic russula"] = { "Ravage Health", "Ravage Magicka", "Ravage Stamina", "Entrapment" },
    ["fleshfly larva"] = { "Ravage Stamina", "Vulnerability", "Gradual Ravage Health", "Vitality" },
    ["imp stool"] = { "Ravage Stamina", "Increase Armor", "Maim", "Enervation" },
    ["lady's smock"] = { "Restore Magicka", "Breach", "Increase Spell Power", "Spell Critical" },
    ["luminous russula"] = { "Restore Health", "Ravage Stamina", "Maim", "Hindrance" },
    ["mountain flower"] = { "Restore Health", "Restore Stamina", "Increase Armor", "Maim" },
    ["mudcrab chitin"] = { "Increase Spell Resist", "Increase Armor", "Protection", "Defile" },
    ["namira's rot"] = { "Spell Critical", "Unstoppable", "Invisible", "Speed" },
    ["nightshade"] = { "Ravage Health", "Protection", "Gradual Ravage Health", "Defile" },
    ["nirnroot"] = { "Ravage Health", "Uncertainty", "Enervation", "Invisible" },
    ["powdered mother of pearl"] = { "Speed", "Protection", "Lingering Health", "Vitality" },
    ["scrib jelly"] = { "Ravage Magicka", "Speed", "Vulnerability", "Lingering Health" },
    ["spider egg"] = { "Invisible", "Hindrance", "Lingering Health", "Defile" },
    ["stinkhorn"] = { "Ravage Health", "Ravage Stamina", "Fracture", "Increase Weapon Power" },
    ["torchbug thorax"] = { "Fracture", "Enervation", "Detection", "Vitality" },
    ["vile coagulant"] = { "Ravage Health", "Restore Magicka", "Protection", "Timidity" },
    ["violet coprinus"] = { "Ravage Health", "Ravage Magicka", "Breach", "Increase Spell Power" },
    ["water hyacinth"] = { "Restore Health", "Spell Critical", "Weapon Critical", "Entrapment" },
    ["white cap"] = { "Ravage Magicka", "Increase Spell Resist", "Cowardice", "Detection" },
    ["wormwood"] = { "Weapon Critical", "Unstoppable", "Detection", "Hindrance" },
}

AAW.traitCancels = {
    ["Restore Health"] = "Ravage Health",
    ["Ravage Health"] = "Restore Health",
    ["Restore Magicka"] = "Ravage Magicka",
    ["Ravage Magicka"] = "Restore Magicka",
    ["Restore Stamina"] = "Ravage Stamina",
    ["Ravage Stamina"] = "Restore Stamina",
    ["Increase Armor"] = "Fracture",
    ["Fracture"] = "Increase Armor",
    ["Increase Spell Resist"] = "Breach",
    ["Breach"] = "Increase Spell Resist",
    ["Increase Weapon Power"] = "Maim",
    ["Maim"] = "Increase Weapon Power",
    ["Increase Spell Power"] = "Cowardice",
    ["Cowardice"] = "Increase Spell Power",
    ["Weapon Critical"] = "Uncertainty",
    ["Uncertainty"] = "Weapon Critical",
    ["Spell Critical"] = "Enervation",
    ["Enervation"] = "Spell Critical",
    ["Detection"] = "Invisible",
    ["Invisible"] = "Detection",
    ["Unstoppable"] = "Hindrance",
    ["Hindrance"] = "Unstoppable",
    ["Speed"] = "Entrapment",
    ["Entrapment"] = "Speed",
    ["Protection"] = "Vulnerability",
    ["Vulnerability"] = "Protection",
    ["Vitality"] = "Defile",
    ["Defile"] = "Vitality",
    ["Lingering Health"] = "Gradual Ravage Health",
    ["Gradual Ravage Health"] = "Lingering Health",
    ["Heroism"] = "Timidity",
    ["Timidity"] = "Heroism",
}



-- Enchanting rune archive.
-- This is Aldren's starting notebook for the Enchanting Desk.
-- The add-on will use it to choose gentle translation lessons.
AAW.runeTranslations = {
    -- Aspect runes
    ["ta"] = { category = "aspect", meaning = "Base", rank = 1 },
    ["jejota"] = { category = "aspect", meaning = "Fine", rank = 2 },
    ["denata"] = { category = "aspect", meaning = "Superior", rank = 3 },
    ["rekuta"] = { category = "aspect", meaning = "Artifact", rank = 4 },
    ["kuta"] = { category = "aspect", meaning = "Legendary", rank = 9, rare = true },

    -- Essence runes
    ["oko"] = { category = "essence", meaning = "Health", rank = 1 },
    ["makko"] = { category = "essence", meaning = "Magicka", rank = 2 },
    ["deni"] = { category = "essence", meaning = "Stamina", rank = 3 },
    ["okoma"] = { category = "essence", meaning = "Health Recovery / Decrease Health", rank = 4 },
    ["makkoma"] = { category = "essence", meaning = "Magicka Recovery / Reduce Spell Cost", rank = 5 },
    ["denima"] = { category = "essence", meaning = "Stamina Recovery / Reduce Feat Cost", rank = 6 },
    ["deteri"] = { category = "essence", meaning = "Armor / Crushing", rank = 7 },
    ["okori"] = { category = "essence", meaning = "Power / Weakening", rank = 8 },
    ["meip"] = { category = "essence", meaning = "Shock", rank = 9 },
    ["rakeipa"] = { category = "essence", meaning = "Flame", rank = 10 },
    ["dekeipa"] = { category = "essence", meaning = "Frost", rank = 11 },
    ["haoko"] = { category = "essence", meaning = "Disease", rank = 12 },
    ["kuoko"] = { category = "essence", meaning = "Poison", rank = 13 },
    ["kaderi"] = { category = "essence", meaning = "Shield / Bashing", rank = 14 },
    ["taderi"] = { category = "essence", meaning = "Physical Harm", rank = 15 },
    ["makderi"] = { category = "essence", meaning = "Spell Harm", rank = 16 },
    ["oru"] = { category = "essence", meaning = "Potion Aid", rank = 17 },
    ["indeko"] = { category = "essence", meaning = "Prismatic Recovery / Reduce Cost", rank = 18, rare = true },
    ["hakeijo"] = { category = "essence", meaning = "Prismatic", rank = 19, rare = true },

    -- Potency runes, additive
    ["jora"] = { category = "potency", meaning = "Develop", polarity = "add", rank = 1 },
    ["porade"] = { category = "potency", meaning = "Add", polarity = "add", rank = 2 },
    ["jera"] = { category = "potency", meaning = "Increase", polarity = "add", rank = 3 },
    ["jejora"] = { category = "potency", meaning = "Raise", polarity = "add", rank = 4 },
    ["odra"] = { category = "potency", meaning = "Gain", polarity = "add", rank = 5 },
    ["pojora"] = { category = "potency", meaning = "Supplement", polarity = "add", rank = 6 },
    ["edora"] = { category = "potency", meaning = "Boost", polarity = "add", rank = 7 },
    ["jaera"] = { category = "potency", meaning = "Advance", polarity = "add", rank = 8 },
    ["pora"] = { category = "potency", meaning = "Augment", polarity = "add", rank = 9 },
    ["denara"] = { category = "potency", meaning = "Strengthen", polarity = "add", rank = 10 },
    ["rera"] = { category = "potency", meaning = "Exaggerate", polarity = "add", rank = 11 },
    ["derado"] = { category = "potency", meaning = "Empower", polarity = "add", rank = 12 },
    ["rekura"] = { category = "potency", meaning = "Magnify", polarity = "add", rank = 13 },
    ["kura"] = { category = "potency", meaning = "Intensify", polarity = "add", rank = 14 },
    ["rejera"] = { category = "potency", meaning = "Amplify", polarity = "add", rank = 15 },
    ["repora"] = { category = "potency", meaning = "Superb", polarity = "add", rank = 16 },

    -- Potency runes, subtractive
    ["jode"] = { category = "potency", meaning = "Reduce", polarity = "sub", rank = 1 },
    ["notade"] = { category = "potency", meaning = "Subtract", polarity = "sub", rank = 2 },
    ["ode"] = { category = "potency", meaning = "Shrink", polarity = "sub", rank = 3 },
    ["tade"] = { category = "potency", meaning = "Decrease", polarity = "sub", rank = 4 },
    ["jayde"] = { category = "potency", meaning = "Deduct", polarity = "sub", rank = 5 },
    ["edode"] = { category = "potency", meaning = "Lower", polarity = "sub", rank = 6 },
    ["pojade"] = { category = "potency", meaning = "Diminish", polarity = "sub", rank = 7 },
    ["rekude"] = { category = "potency", meaning = "Weaken", polarity = "sub", rank = 8 },
    ["hade"] = { category = "potency", meaning = "Lessen", polarity = "sub", rank = 9 },
    ["idode"] = { category = "potency", meaning = "Impair", polarity = "sub", rank = 10 },
    ["pode"] = { category = "potency", meaning = "Remove", polarity = "sub", rank = 11 },
    ["kedeko"] = { category = "potency", meaning = "Drain", polarity = "sub", rank = 12 },
    ["rede"] = { category = "potency", meaning = "Deprive", polarity = "sub", rank = 13 },
    ["kude"] = { category = "potency", meaning = "Negate", polarity = "sub", rank = 14 },
    ["jehade"] = { category = "potency", meaning = "Divest", polarity = "sub", rank = 15 },
    ["itade"] = { category = "potency", meaning = "Superb", polarity = "sub", rank = 16 },
}
