-- Aldren's Grandmaster Workshop: Provisioning Knowledge Catalogue
-- Data only. This file starts no timers, opens no windows, and queries no ESO APIs.
-- Food/drink recipes and Provisioning furnishing designs are kept as separate knowledge sets.

AldrensGrandmasterWorkshop_ProvisioningKnowledge = {
    schemaVersion = 1,
    catalogueVersion = "1.3.12",
    recipeCompendiumAchievementId = 1028,
    recipeCompendiumRequired = 100,
    foodDrinkRecipeNames = {
        "Abecean Brandy",
        "Acai Dry Mazte",
        "Acai Tonic Infusion",
        "Aetherial Ambrosia",
        "Aetherial Tea",
        "Akaviri Pork Fried Rice",
        "Alabaster Honey Rum",
        "Alcaire Festival Sword-Pie",
        "Alik'r Beets with Goat Cheese",
        "Anequina Stout",
        "Animate-the-Dead",
        "Apple Baked Fish",
        "Apple Cobbler Supreme",
        "Apple Mashed Potatoes",
        "Apple-Eidar Cheese Salad",
        "Aqua Vitae",
        "Arenthia's Empty Tankard Frittata",
        "Arenthian Brandy",
        "Argonian Mud-Nectar",
        "Argonian Pumpkin Stew",
        "Argonian Saddle-Cured Rabbit",
        "Artaeum Pickled Fish Bowl",
        "Artaeum Takeaway Broth",
        "Ash-Hopper Dumplings on Scathecraw",
        "Ashlander Nix-Hound Chili",
        "Ashlander Ochre Mash",
        "Athlete's Guzzle",
        "Aunt Alessia's Pork Chops",
        "Azura's Rose Tea",
        "Baby Carrots in Moon-Sugar Glaze",
        "Baked Apples",
        "Baked Potato",
        "Baked Sole with Bananas",
        "Balfiera Herbal Tonic",
        "Balmora Cabbage Biscuits",
        "Banana Millet Muffin",
        "Banana Surprise",
        "Bananas in Moon-Sugar Syrup",
        "Barley Nectar",
        "Battaglir Chowder",
        "Beef and Beets Pasty",
        "Beef Stew",
        "Beet-Glazed Pork",
        "Bergama Warning Fire",
        "Berrymead Tonic",
        "Berveza Vitae",
        "Betnikh Twice-Spiked Ale",
        "Bewitched Sugar Skulls",
        "Bitter Kaveh",
        "Bitter Remorse Ale",
        "Bitter Ritual Tea",
        "Bitter Tea",
        "Bitterlemon Tea",
        "Black Coffee",
        "Black Marsh Wamasu Loin",
        "Black Night Cordial",
        "Blacklight Ginger Mazte",
        "Blacklight Oxen Meatballs",
        "Blackwood Mint Chai",
        "Blackwood Stuffed Banana Leaves",
        "Blue Banekin Beer",
        "Blue Road Marathon",
        "Boethiah's Breath",
        "Bog-Iron Ale",
        "Boiled Creme Treat",
        "Borscht",
        "Bowl of \"Peeled Eyeballs\"",
        "Braised Rabbit with Spring Vegetables",
        "Braised Sweetmeats",
        "Bravil Bitter Barley Beer",
        "Bravil Mead",
        "Bravil Melon Salad",
        "Bravil's Best Beet Risotto",
        "Breton Bubble-and-Squeak",
        "Breton Pint of Bitters",
        "Breton Pork Sausage",
        "Bruma Jugged Rabbit",
        "Busy Bee Brew",
        "Camlorn Mint Tea",
        "Camlorn Pork Sausage",
        "Camlorn Sweet Brown Ale",
        "Candied Jester's Coins",
        "Cantaloupe Bread",
        "Capon Tomato-Beet Casserole",
        "Caramelized Goat Nibbles",
        "Cardiac Arrest",
        "Carrot Cheesecake",
        "Carrot Soup",
        "Celestial Tonic Tea",
        "Centurion's Friend Kaveh",
        "Cheese Pork Schnitzel",
        "Cheesemonger's Salad",
        "Chevre-Radish Salad with Pumpkin Seeds",
        "Cheydinhal Sherry",
        "Chicken and Biscuits",
        "Chicken Breast",
        "Chicken-and-Banana Fried Rice",
        "Chorrol Corn on the Cob",
        "Chthonic Tonic",
        "Cinnamon Gorapples",
        "Cinnamon Grape Jelly",
        "Clamberskull",
        "Clan Mother's Banana Pilaf",
        "Clan Mother's Cordial",
        "Clarified Rose Lager",
        "Clarified Syrah Wine",
        "Clavicus Vines Chenin Blanc",
        "Clockwork Citrus Filet",
        "Cloudrest Clarified Coffee",
        "Cloudrest Golden Ale",
        "Cloudy Dregs Inn Bouillabaisse",
        "Coldharbour Daedrat Snacks",
        "Colovian Amber Ale",
        "Colovian Beef Noodle Soup",
        "Colovian Ginger Beer",
        "Colovian Roast Turkey",
        "Colovian War Torte",
        "Comberry Bourbon",
        "Comberry Chai",
        "Comberry Citrus Quencher",
        "Comberry Tonic",
        "Combwort Flatbread",
        "Comely Wench Whiskey",
        "Corinthe Corn Beef",
        "Corinthean Roast Kagouti",
        "Cornerclub Kaveh",
        "Corrupting Bloody Mara",
        "Craglorn Skavenger Stew",
        "Crawdad Quiche",
        "Creamcheese Frosted Gorapple Cake",
        "Creme de Menthe",
        "Crisp and Crunchy Pumpkin Snack Skewer",
        "Crispy Cheddar Chicken",
        "Crow's Nest Rye",
        "Crunchy Spider Skewer",
        "Crystal Clarity",
        "Crystal Tower Whiskey",
        "Curried Kwama Scrib Risotto",
        "Cyrodilic Cornbread",
        "Cyrodilic Pumpkin Fritters",
        "Dancing Grandma",
        "Dark Seducer",
        "Dawnstar Sun's Dusk Chowder",
        "Deregulated Mushroom Stew",
        "Deshaan Honeydew Hors D'oeuvres",
        "Dibella's Kiss Tea",
        "Direnni Hundred-Year Rabbit Bisque",
        "Double Clarified Mazte",
        "Dragonstar Radish Kebabs",
        "Dragontail Blended Whisky",
        "Dreugh Spit",
        "Drowned Sailor Ale",
        "Drunken Goat Cheese with Radishes",
        "Dubious Camoran Throne",
        "Duck Soup",
        "Dunmeri Jerked Horse Haunch",
        "Eidar Banana-Radish Vichyssoise",
        "Eidar Radish Salad",
        "Elinhir Qishr",
        "Elinhir Roast Antelope",
        "Elsweyr Corn Fritters",
        "Elsweyr Fondue",
        "Eltheric Hooch",
        "Elven Maiden Tea",
        "Enemies Explode",
        "Enlightenment Tea",
        "Every-Morndas Casserole",
        "Falinesti Forbidden Fruit",
        "Falkreath Meat Loaf",
        "Falkreath Rosy Mead",
        "Fifth Legion Porter",
        "First Kiss Tea",
        "Firsthold Fruit and Cheese Plate",
        "Fishy Stick",
        "Five-Fireball Infusion",
        "Flank Steak",
        "Flowing Bowl Green Port",
        "Forge-Wife's Spudmelon Pie",
        "Four-Eye Grog",
        "Fredas Night Infusion",
        "Fresh Apples and Eidar Cheese",
        "Fricasseed Rabbit with Radishes",
        "Fried Green Tomatoes",
        "Frosted Brains",
        "Frostfall Pork Roast",
        "Frothy Sargassum",
        "Fulmination Ale",
        "Fyr's Hyperagonal Potation",
        "Garlic Cod with Potato Crust",
        "Garlic Guar Stuffed Grape Leaves",
        "Garlic Mashed Potatoes",
        "Garlic Pumpkin Seeds",
        "Garlic Radishes a la Kvatch",
        "Garlic-and-Pepper Venison Steak",
        "Gazelle Cutlet with Minced Pumpkin",
        "Ghastly Eye Bowl",
        "Gilane Garlicky Greens",
        "Ginger Guar Smoothie",
        "Ginger Port",
        "Ginger Wheat Beer",
        "Gingerose Tea",
        "Ginkgo Double Brandy",
        "Ginkgo Lightning",
        "Ginkgo Tonic",
        "Ginkgo Twist Tonic",
        "Ginseng Sling",
        "Ginseng Tonic",
        "Goatherd's Pie",
        "Goblin-Style Grilled Rat",
        "Gods-Blind-Me",
        "Gold Coast Mudcrab Fries",
        "Golden Lager",
        "Gossamer Mazte",
        "Grandmam's Roast Rabbit",
        "Grandpa's Bedtime Tonic",
        "Granny's Eel Pie",
        "Grape Preserves",
        "Grape-Glazed Bantam Guar",
        "Grapes and Ash Yam Falafel",
        "Greef",
        "Green Bananas with Garlic",
        "Green Salad",
        "Green Scourgut Tea",
        "Grilled Camel on Cornbread",
        "Grilled Hare",
        "Grilled Timber Mammoth Kebabs",
        "Guarana Tonic",
        "Hag Fen Pumpkin Pie",
        "Hagraven's Tonic",
        "Hammerfell Antelope Stew",
        "Happy Ogrim Amber Ale",
        "Hare in Garlic Sauce",
        "Hasphat's Sticky Guar Tonic",
        "Heart's Day Rose Tea",
        "Hearthfire Harvest Pilaf",
        "Hearthfire Vegetable Salad",
        "Hearty Garlic Corn Chowder",
        "Hearty Sun's Dusk Soup",
        "Hello Handsome Porter",
        "Herbflower Tea",
        "High Rock Rose and Rye",
        "Highland Rabbit Stew",
        "Hircine's Meat Loaf",
        "Hissmir Fish-Eye Rye",
        "Honest Lassie Honey Tea",
        "Honey Nut Treat",
        "Honey Rye",
        "Honeyberry Tea",
        "Honeyhips Brown Ale",
        "Hopscotch",
        "Horker Loaf",
        "Horker's Breath",
        "House Hlaalu Pumpkin Risotto",
        "Hunt-Wife's Beef Radish Stew",
        "Hunt-Wife's Grog",
        "Hunter's Pie",
        "Imperial Stout",
        "Imperial Stuffed Piglet",
        "Indoril Radish Tartlets",
        "Infernal Infusion",
        "Isinmate Infusion",
        "Jagga-Drenched \"Mud Ball\"",
        "Jasmine Moonshine",
        "Jasmine Tea",
        "Jasminger Tea",
        "Jasminkgo Tonic",
        "Jasrana Tea Tonic",
        "Jephre's Earthbone Beer",
        "Jerall View Inn Carrot Cake",
        "Jewels of Misrule",
        "Jugged Rabbit in Preserves",
        "Kagouti Kick Mazte",
        "Kaveh Stout",
        "Kelp Kaveh",
        "Khajiiti Apple Spanakopita",
        "Khajiiti Sweet-Stuffed Duck",
        "Khenarthi's Wings Chai",
        "Kragenmoor Pickled Pumpkin",
        "Kragenmoor Zinger Mazte",
        "Kvatch Watch Grenache",
        "Kwama Egg Omelet",
        "Kwama Egg Quiche",
        "Last Seed Salad",
        "Late Hearthfire Vegetable Tart",
        "Late-Summer Corn Slaw",
        "Lava Foot Soup-and-Saltrice",
        "Lemon Flower Mazte",
        "Lemonic Invigoration",
        "Lillandril Summer Sausage",
        "Lillandril Tonic Tea",
        "Lilmoth Garlic Hagfish",
        "Longfin Pasty with Melon Sauce",
        "Lotus Tea",
        "Lusty Argonian Maid Mazte",
        "Mage's Gorapple Porridge",
        "Mage's Mead",
        "Malacath's Hammer",
        "Mammoth Snout Pie",
        "Maormer Tea",
        "Markarth Mead",
        "Markarth Short Pig",
        "Mate Infusion",
        "Mazte",
        "Mead de Menthe",
        "Meady-Matey Infusion",
        "Melon Carpaccio",
        "Melon Jelly",
        "Melon-Baked Parmesan Pork",
        "Melon-Chevre Salad",
        "Melon-Radish Salad",
        "Mermaid Whiskey",
        "Mid Year Green Salad",
        "Midnight Ritual Tea",
        "Millet and Beef Stuffed Peppers",
        "Millet-Stuffed Pork Loin",
        "Minotaur Slumgullion",
        "Mint Chai",
        "Mint Mudcrab Mojito",
        "Mintmead Kaveh",
        "Mistral Banana Bread",
        "Mistral Banana-Bunny Hash",
        "Molten War Torte",
        "Monkeypants Mazte",
        "Monkeypig Cutlets",
        "Morning Reveille Tea",
        "Mother Mara's Savory Rabbit Stew",
        "Mournhold Twister",
        "Mudcrab Corn Fritters",
        "Mulled Wine",
        "Muthsera's Remorse",
        "Mythic Aetherial Ambrosia",
        "Narsis Bantam Guar Hash",
        "Narsis Wickwheat Ale",
        "Necrom Beetle-Cheese Poutine",
        "Necrom Nights Mazte",
        "Nereid Wine",
        "Nibenese Fricasseed Fawn",
        "Nibenese Garlic Carrots",
        "Night-Grog",
        "Nocturnal's Everblack Coffee",
        "Nord Warrior Potato Porridge",
        "Numidium Brandy",
        "Nut Brown Ale",
        "Old Aldmeri Orphan Gruel",
        "Old Clear-Eye Whiskey",
        "Old Hegathe Lemon Kaveh",
        "Old Orsinium Blood Soup",
        "Old Sweetheart Stout",
        "Orcish Bratwurst on Bun",
        "Orcish No-Rhubarb Salad",
        "Orcrest Agony Pale Ale",
        "Orcrest Garlic Apple Jelly",
        "Ordinator's Beetle-Cheese Soup",
        "Orsinium Pink Zinfandel",
        "Orzorga's Blood Price Pie",
        "Orzorga's Red Frothgar",
        "Orzorga's Smoked Bear Haunch",
        "Orzorga's Tripe Trifle Pocket",
        "Oyster Tomato Orzo",
        "Pack Leader's Bone Broth",
        "Palace of Kings Ginger Beer",
        "Pan-Fried Trout",
        "Parmesan Eels in Watermelon",
        "Parrot-and-Pumpkin Salad",
        "Peacock Pie",
        "Pellitine Tomato Rice",
        "Pickled Carrot Slurry",
        "Pink Profundity",
        "Pink Wisdom Tea",
        "Pirate Queen Mint Tea",
        "Pirate's Jig Tonic",
        "Planked Abecean Longfin",
        "Pondwater Tea",
        "Pork and Bitter Melon",
        "Port Hunding Cheese Fries",
        "Port Hunding Pinot Noir",
        "Potato Rice Blintzes",
        "Potato-Stuffed Roast Pheasant",
        "Potentate's Supreme Cioppino",
        "Princess's Delight",
        "Psijic Ambrosia",
        "Psijic Order Pigs-in-a-Blanket",
        "Psijic Sage's Mazte",
        "Puckermint Tea",
        "Pumpkin Cheesecake",
        "Pumpkin Corn Fritters",
        "Pumpkin Puree",
        "Pumpkin-Stuffed Fellrunner",
        "Punkin Bunny",
        "Purifying Bloody Mara",
        "Pyandonea Merlot",
        "Qhalua Liqueur",
        "Rabbit Corn Chowder",
        "Rabbit Gnocchi Ragu",
        "Rabbit Haunch with Cheese Grits",
        "Rabbit Loin with Bitter Greens",
        "Rabbit Millet Pilaf",
        "Rabbit Pasty",
        "Radishes in Rice",
        "Rajhin's Sugar Claws",
        "Raven Rock Baked Ash Yams",
        "Red Deer Stew",
        "Red Hippocras",
        "Red Queen's Eye-Opener",
        "Red Rye Beer",
        "Redguard Venison Pie",
        "Redoran Peppered Melon",
        "Riekling Suckling Bristleback",
        "Riften Rye",
        "Rihad Beet and Garlic Salad",
        "Rihad Qishr",
        "Rimmen Raisin Cookies",
        "Rimmen Sour Bock",
        "Rislav's Righteous Red Kvass",
        "Roast Corn",
        "Roast Pig",
        "Roast Venison",
        "Roasted Beet and Millet Salad",
        "Rose Herbal Tea",
        "Rose Lager",
        "Rosy Disposition Tonic",
        "Rosy Island Ale",
        "Rude Awakening",
        "Rumare Slaughterfish Pie",
        "Rye-in-your-Eye",
        "Sailor's Second Wind",
        "Saint Pelin's Tawny Port",
        "Salmon Steak Supreme",
        "Salmon with Radish Slaw",
        "Salted Cod",
        "Sanguine's Temptation",
        "Savory Banana Cornbread",
        "Savory Mid Year Preserves",
        "Savory Thorn Cornbread",
        "Savory-Sweet Fried Kale",
        "Seaberry Tonic",
        "Seaflower Tea",
        "Seared Slaughterfish with Mammoth Cheese",
        "Senchal Curry Fish and Rice",
        "Senchal Dancer Tonic",
        "Senche-Tiger Single Malt",
        "Serene Awareness",
        "Seven Year Beer",
        "Shepherd's Pie",
        "Shimmerene Tonic",
        "Shornhelm Ox-Tail Soup",
        "Silver Lotusberry Tea",
        "Silverside Perch Pudding",
        "Sipping Imga Tonic",
        "Skingrad Cabbage Soup",
        "Skingrad Muscat",
        "Skyrim Jazbay Crostata",
        "Sload Slime",
        "Slow-Simmered Rabbit Goulash",
        "Snow Bear Glow-Wine",
        "Solitude Salmon-Millet Soup",
        "Solstheim Elk and Scuttle",
        "Soothing Bard's-Throat Tea",
        "Soothing Sundas Tonic",
        "Sorry, Honey Lager",
        "Sour Gin Fizz",
        "Sour Guar Shein",
        "Sour Mash",
        "Sourflower Tea",
        "Spiceberry Chai",
        "Spiced Mazte",
        "Spicy Beet Salad",
        "Spicy Wyress Wine",
        "Spinner's Taboo Salad",
        "Spriggan Sap",
        "Spring-Loaded Infusion",
        "Stalwart Stout",
        "Stand-Me-Up Lager",
        "Steamed Radishes",
        "Stendarr's Vigilance Ginger Ale",
        "Sticky Pork and Radish Noodles",
        "Stir-Fried Garlic Beef",
        "Stirk Pork-and-Beets",
        "Stormhold Baked Bananas",
        "Strapping Lad Tonic",
        "Stros M'Kai Grilled Seagull",
        "Stuffed Capon",
        "Stuffed Grape Leaves",
        "Stuffed Venison Haunch",
        "Sujamma",
        "Summer Mazte",
        "Summer Sky Pale Ale",
        "Summer Sundas Soup",
        "Summerset Rainbow Pie",
        "Sun's Height Pudding",
        "Sun-Dried Caravan Provisions",
        "Surilie Bros. White Merlot",
        "Surilie Syrah Wine",
        "Sweet and Sour Port",
        "Sweet Dreams Tea",
        "Sweet Dune Gnocchi",
        "Sweet Horker Stew",
        "Sweet Lemonale",
        "Sweet Persistence",
        "Sweet Potatoes",
        "Sweet Sanguine Apples",
        "Sweet Scamp Mazte",
        "Sweet Scented Infusion",
        "Sweet Skeever Gumbo",
        "Sweet Slaughterfish Tea",
        "Sweetberry Tonic",
        "Sweetroll",
        "Sweetsting Tea",
        "Sylph Gin",
        "Taneth Chili Cheese Corn",
        "Taneth Coffee",
        "Tarragon Chicken",
        "Tawny Port",
        "Tears of Joy",
        "Telvanni Tea",
        "Ten Ogres Tonic",
        "Ten-Foot Beer",
        "Tenmar Millet-Carrot Couscous",
        "The Emperor's Venison Fricassee",
        "The Secret Chef's Beet Crostata",
        "The Secret Chef's Pork Roast",
        "The Skald-King's Patty Melt",
        "Thrassian Chai",
        "Thrice-Baked Gorapple Pie",
        "Timber Mammoth Ale",
        "Tingle Tonic Tea",
        "Toasted Millet Salad",
        "Tomato Borscht",
        "Tomato Garlic Chutney",
        "Tomato Soup",
        "Tonal Architect Tonic",
        "Tonic of Portent Favor",
        "Tonsil Tingle Tonic",
        "Torval Mint Tea",
        "Tranquility Pale Ale",
        "Treacleberry Tea",
        "Truth-Glimpse",
        "Tsaesci Tea",
        "Twenty-Four-Raven Pie",
        "Twice-Baked Potatoes",
        "Two-Zephyr Tea",
        "Ultimate Riverhold Beef Pasty",
        "Vaermina's Nightmare",
        "Velothi Cabbage Soup",
        "Velothi View Vintage Malbec",
        "Venison Pasty",
        "Venison Stuffed Grape Leaves",
        "Vigilance Gold Ale",
        "Vivec's Gingergreen Chai",
        "Vvardenfell Ash Yam Loaf",
        "Vvardenfell Cliff Racer Ragout",
        "Vvardenfell Flin",
        "Wamasu Spew",
        "West Weald Corn Chowder",
        "West Weald Wallop",
        "Whiskey Sour",
        "White-Eye Whiskey",
        "White-Gold War Torte",
        "Whiterun Cheese-Baked Trout",
        "Wide-Eye Double Rye",
        "Wild-Boar-and-Beets",
        "Winter Rose Tea",
        "Witchmother's Party Punch",
        "Witchmother's Potent Brew",
        "Withered Tree Inn Venison Pot Roast",
        "Wizard's Whiskey",
        "Xanmeer Brandy",
        "Yellow Goblin Tonic",
        "Yellow Oxen Loaf",
        "Yerba Syrah Wine",
        "Yerba Zinger Tonic",
        "Yokudan Sorrow Bourbon",
        "Ysgramor's Harbinger Lager",
    },
    provisioningDesignNames = {
        "Alinor Amphora, Delicate",
        "Alinor Amphora, Embossed",
        "Alinor Amphora, Portrait",
        "Alinor Amphora, Slender",
        "Alinor Bowl, Millet",
        "Alinor Grape Stomping Tub",
        "Alinor Meal, Complete Setting",
        "Alinor Meal, Individual",
        "Alinor Pie Dish, Cherry Pie",
        "Alinor Urn, Gilded",
        "Alinor Urn, Stemmed",
        "Apocrypha Tree, Spore",
        "Apple Pie, Lattice Crust",
        "Apple, Display",
        "Argonian Bone Chimes",
        "Argonian Cup, Short",
        "Argonian Light, Stick",
        "Argonian Lights, Branch",
        "Argonian Post, Frilled",
        "Argonian Skull, Crocodile",
        "Argonian Skull, Lizard",
        "Argonian Snakes on a Rope",
        "Argonian Totem of Skulls",
        "Argonian Totem of the Snake",
        "Argonian Totem, Frilled Skull",
        "Argonian Totem, Painted Skull",
        "Argonian Tree of Lights",
        "Ashlander Platter, Bread and Cheese",
        "Ashlander Platter, Ceramic",
        "Baked Potato, Display",
        "Banana, Wax",
        "Basket of Apples",
        "Basket of Apples, Full",
        "Basket of Corn",
        "Basket of Gourds",
        "Basket of Lettuce",
        "Basket of Tomatoes",
        "Beet String, Display",
        "Beets, Display",
        "Blackwood Provisioning Station",
        "Bowl of Guts",
        "Bowl of Worms",
        "Bowl of Worms, Large",
        "Box of Plums",
        "Bread Loaves, Round",
        "Bread, Braided",
        "Bread, Hearty Loaves",
        "Bread, Round",
        "Breton Amphora, Glazed",
        "Breton Chamberstick, Short",
        "Breton Chamberstick, Tall",
        "Breton Pitcher, Ceramic",
        "Breton Pottery, Lid",
        "Breton Urn, Glazed",
        "Breton Vase, Ceramic",
        "Breton Vase, Glazed",
        "Candle Set, Ritual",
        "Candle, Group",
        "Carnaval Fan",
        "Carrots, Wax",
        "Cheese Wedge",
        "Clockwork Bowl, Large Nutriment Paste",
        "Clockwork Bowl, Nutriment Paste",
        "Clockwork Cup, Recycled Water",
        "Clockwork Goblet, Recycled Water",
        "Clockwork Meal, Dish",
        "Clockwork Meal, Plate",
        "Clockwork Paste Dispenser, Empty",
        "Coconut Bunch, Display",
        "Colovian Bowl, Grapes",
        "Colovian Grape Basket, Wax",
        "Colovian Grape Vat, Large",
        "Colovian Meal, Cheese Board",
        "Colovian Meal, Grape Board",
        "Colovian Meal, Poultry",
        "Colovian Serving Dish, Cheese",
        "Colovian Tray, Honeycomb",
        "Common Bowl of Soup, Display",
        "Common Bowl of Stew, Display",
        "Common Candle, Lasting",
        "Common Candle, Set",
        "Common Candles, Pair",
        "Cured Meat",
        "Cured Meat Chunk",
        "Cured Meat Chunks",
        "Cured Meat Hock",
        "Cured Meat Pile",
        "Cured Meat Shank",
        "Cured Meats",
        "Daedric Candles, Group",
        "Daedric Candles, Ritual Set",
        "Dawnwood Basket, Antlers",
        "Dawnwood Decor, Curved Bone",
        "Dawnwood Decor, Wrapped Bone",
        "Dawnwood Lantern, Table",
        "Dawnwood Meal, Delicacy",
        "Dawnwood Meal, Flan",
        "Dawnwood Meal, Meat",
        "Dawnwood Platter, Feast",
        "Dawnwood Soup, Pumpkin",
        "Dawnwood Tray, Fish",
        "Dawnwood Wind Chimes, Bone",
        "Dragonfruit, Wax",
        "Dres Bowl, Dinner",
        "Dres Bowl, Empty",
        "Dres Bowl, Saltrice Mash",
        "Dres Bowl, Serving",
        "Dres Candles, Meditation",
        "Dres Cup, Empty Greef",
        "Dres Cup, Empty Mazte",
        "Dres Cup, Empty Sujamma",
        "Dres Cup, Greef",
        "Dres Cup, Mazte",
        "Dres Cup, Sujamma",
        "Druid Mug, Clay",
        "Druidic Bowl, Clay",
        "Druidic Chandelier, Firesong",
        "Druidic Gourd Bird Feeder",
        "Druidic Gourd Candle, Hanging",
        "Druidic Incense Burner, Clay",
        "Druidic Oven, Stone",
        "Druidic Pot, Clay",
        "Druidic Wind Chimes, Gourd",
        "Drumstick",
        "Dwarven Candles, Cup",
        "Dwarven Candles, Plate",
        "Dwarven Candlestick, Laboratory",
        "Dwarven Candlestick, Orrery",
        "Dwarven Dinner Bowl, Hearty Stew",
        "Dwarven Plate, Full Breakfast",
        "Dwarven Serving Dish, Vegetable Soup",
        "Elsweyr Bowl, Deep Ceramic",
        "Elsweyr Bowl, Shallow Ceramic",
        "Elsweyr Bread Basket, Feast-Day",
        "Elsweyr Candle, Saucer",
        "Elsweyr Fish, Displayed",
        "Elsweyr Meal, Roasted Chicken Pieces",
        "Elsweyr Meal, Root Vegetables",
        "Elsweyr Plate, Rough",
        "Elsweyr Pot, Stoneware",
        "Elsweyr Sconce, Candle Carved",
        "Elsweyr Sconce, Candle Elegant",
        "Elsweyr Sconce, Candle Engraved",
        "Elsweyr Sconce, Candle Shielded",
        "Elsweyr Spice Display, Matcha Green",
        "Elsweyr Spice Display, Saffron Red",
        "Elsweyr Spice Display, Turmeric Yellow",
        "Elsweyr Steamer, Ceramic",
        "Fargrave Box of Fruit",
        "Fargrave Box of Grapes",
        "Fargrave Bread and Sweetrolls",
        "Fargrave Bread, Baguettes",
        "Fargrave Bread, Round Loaves",
        "Fargrave Bread, Various Loaves",
        "Fargrave Corn, Bunch",
        "Fargrave Fish Pile, Deadlands Trout",
        "Fargrave Fish Pile, Marinated Trout",
        "Fargrave Ham",
        "Fargrave Meats",
        "Fargrave Sausages",
        "Fargrave Tomato Bunch",
        "Fish, Large",
        "Fish, Medium",
        "Fish, Small",
        "Fruit Arrangement, Tide-Born",
        "Fruit Bunch, Display",
        "Goblet, Wine",
        "Grapes, Wax",
        "Green Coconut Bunch, Display",
        "Grub Kebabs",
        "Ham, Display",
        "Hearty Bread",
        "High Isle Crab, Steamed",
        "High Isle Crab, Steamed Pile",
        "High Isle Mussel, Steamed Pile",
        "Honey Jar, Sealed",
        "Honey Pot, Open",
        "Indoril Candelabra, Shrine Chamber",
        "Indoril Candelabra, Temple",
        "Indoril Candelabra, Temple Chamber",
        "Indoril Candle, Temple",
        "Indoril Chandelier, Vine-Covered",
        "Khajiit Bottle, Amber",
        "Khajiit Carafe, Amber",
        "Khajiit Decanter, Amber",
        "Khajiit Flask, Amber",
        "Khajiit Jug, Amber",
        "Khajiit Pitcher, Amber",
        "Khajiit Skooma Bubbler",
        "Khajiit Urn, Amber",
        "Khajiit Vase, Amber",
        "Khajiit Vessel, Amber",
        "Khajiit Vial, Amber",
        "Lemon Slice, Display",
        "Lettuce, Display",
        "Leyawiin Bowl, Lobster Stew",
        "Leyawiin Bowl, Squid Special",
        "Leyawiin Corncobs, Triple",
        "Leyawiin Gravy Boat, Silver",
        "Leyawiin Kylix, Silver",
        "Leyawiin Lettuce, Leaf",
        "Leyawiin Meal, Clams",
        "Leyawiin Meal, Lobster",
        "Leyawiin Meal, Octopus",
        "Leyawiin Meal, Squid",
        "Leyawiin Meal, Vegetables",
        "Leyawiin Mug, Milk",
        "Leyawiin Pie, Octopus",
        "Leyawiin Platter, Seafood",
        "Leyawiin Serving Pot, Lobster Stew",
        "Leyawiin Teacup, Full",
        "Leyawiin Tomatoes, Vine",
        "Lime Slice, Display",
        "Lychee Bowl, Display",
        "Lychee Bunch, Display",
        "Mammoth Cheese, Mastercrafted",
        "Melon, Wax",
        "Miniature Garden, Bottled",
        "Mortar and Pestle",
        "Murkmire Berry Strand",
        "Murkmire Candle, Bone Squat",
        "Murkmire Candle, Bone Tall",
        "Murkmire Candlepost, Driftwood",
        "Murkmire Candlepost, Timber",
        "Murkmire Candles, Bone Group",
        "Murkmire Pot, Handmade",
        "Murkmire Pot, Large Carved",
        "Mussel Bowl, Display",
        "Necrom Bowl, Elegant",
        "Necrom Candle, Elegant",
        "Necrom Candle, Large Square",
        "Necrom Candle, Small Square",
        "Necrom Incense, Mushroom Offering",
        "Necrom Urn, Malachite",
        "Noble Standing Cauldron",
        "Nord Amphora, Glazed",
        "Nord Cauldron, Glazed",
        "Nord Crockpot, Carrot Soup",
        "Nord Pot, Ceramic",
        "Nord Pot, Empty",
        "Nord Pot, Stew",
        "Nord Urn, Braided",
        "Nord Urn, Ceramic",
        "Nord Vase, Bent",
        "Oranges, Bunch",
        "Orcish Bowl, Buffed",
        "Orcish Bowl, Rugged",
        "Orcish Candle Sconce, Horn",
        "Orcish Canister, Rugged",
        "Orcish Capsule, Sealed",
        "Orcish Cask, Rugged",
        "Orcish Goblet, Stone",
        "Orcish Platter, Serving",
        "Orcish Skull Goblet, Full",
        "Orcish Urn, Ceramic",
        "Orcish Urn, Sealed",
        "Orcish Vessel, Sealed Ceramic",
        "Oyster Plate, Display",
        "Peaches, Bunch",
        "Pie Dish, Display",
        "Plums, Bunch",
        "Pot Pie, Display",
        "Potato, Wax",
        "Pottery Wheel, Ever-Turning",
        "Provisioning Station, Elsweyr Grill",
        "Provisioning Station, Solitude Grill",
        "Puddle, Wax",
        "Pumpkin, Display",
        "Pumpkin, Sliced Green",
        "Radish, Wax",
        "Redguard Amphora, Polished",
        "Redguard Cup, Full",
        "Redguard Kabobs, Plate",
        "Redguard Kabobs, Wax",
        "Redguard Pot, Capped",
        "Redguard Pot, Ceramic",
        "Redguard Pot, Hanging Mosaic",
        "Redguard Pot, Lacquered",
        "Redguard Pot, Mosaic",
        "Redguard Pot, Sealed",
        "Redguard Slices, Wax",
        "Redguard Urn, Lacquered",
        "Redguard Urn, Mural",
        "Redguard Vase, Lacquered",
        "Redguard Vessel, Lacquered",
        "Redoran Bowl, Empty",
        "Redoran Bowl, Saltrice Mash",
        "Redoran Cup, Empty",
        "Redoran Cup, Mazte",
        "Seafood Platter, Display",
        "Seahorse Platter, Display",
        "Shark Jaw, Massive",
        "Shell-Tide Hatchery Altar, Replica",
        "Snail Bowl, Display",
        "Solitude Bowl, Berries",
        "Solitude Bowl, Mushrooms",
        "Solitude Bowl, Winter Onions",
        "Solitude Bread, Floral Pattern",
        "Solitude Bread, Long",
        "Solitude Bread, Partial Loaf",
        "Solitude Bread, Rustic Loaf",
        "Solitude Bread, Rustic Sliced",
        "Solitude Breakfast, Eggs and Ham",
        "Solitude Breakfast, Full",
        "Solitude Breakfast, Sausages and Ham",
        "Solitude Camping Pot, Fish Stew",
        "Solitude Candlestick, Horn",
        "Solitude Dinner Bowl, Hearty Stew",
        "Solitude Dinner Bowl, Vegetable Soup",
        "Solitude Drinking Horn, Ivory",
        "Solitude Drying Rack, Stockfish",
        "Solitude Goblet, Knotwork",
        "Solitude Meal, Rustic",
        "Solitude Platter, Ribs",
        "Solitude Pot, Large Ceramic",
        "Solitude Sconce, Horn",
        "Solitude Serving Pot, Hearty Stew",
        "Solitude Serving Pot, Vegetable Soup",
        "Solitude Smoking Rack, Fish",
        "Solitude Smoking Rack, Sausage",
        "Solitude Stein, Rustic",
        "Solitude Tray, Fresh Eel",
        "Solitude Tray, Stockfish",
        "Solitude Urn, Ceramic",
        "Solitude Vase, Large Sealed",
        "Sugar Pumpkin, Wax",
        "Sweetroll",
        "Tangerines, Bunch",
        "Telvanni Bookcase, Tall Fungal",
        "Telvanni Dresser, Large Fungal",
        "Telvanni Meal, Fish Dinner",
        "Telvanni Meal, Fruit Breakfast",
        "Telvanni Meal, Kebab Lunch",
        "Telvanni Mug, Fungal",
        "Telvanni Planter, Fungal",
        "Telvanni Soup, Hearty Mushroom",
        "Telvanni Table, Round Fungal",
        "Tide-Born Art, Decorative Shrimp",
        "Tide-Born Art, Flame Lily",
        "Tide-Born Candleholder, Coral",
        "Tide-Born Candleholder, Stone",
        "Tide-Born Chandelier, Coral",
        "Tide-Born Drying Rack, Fish",
        "Tide-Born Floor Lamp, Coral",
        "Tide-Born Gourd Shaker",
        "Tide-Born Lamp, Coral",
        "Tide-Born Ornament, Painted Coral",
        "Tide-Born Pot, Egg",
        "Tide-Born Pot, Shell-Topped",
        "Tide-Born Sconce, Coral",
        "Tide-Born Windcatcher, Feathered",
        "Vampiric Goblet, Fluted",
        "Vampiric Goblet, Full",
        "Winter Squash, Display",
        "Wood Elf Barrel, Ceramic",
        "Wood Elf Bin, Blue Feathers",
        "Wood Elf Bin, Feathers",
        "Wood Elf Bone Chimes",
        "Wood Elf Bowl, Striped",
        "Wood Elf Cask, Ceramic",
        "Wood Elf Cask, Painted",
        "Wood Elf Cauldron, Ceramic",
        "Wood Elf Censer, Hanging",
        "Wood Elf Cup, Ceramic",
        "Wood Elf Cup, Chipped",
        "Wood Elf Cup, Striped",
        "Wood Elf Fish Dish",
        "Wood Elf Pitcher, Ceramic",
        "Wood Elf Pitcher, Chipped",
        "Wood Elf Pitcher, Marked",
        "Wood Elf Pitcher, Painted",
        "Wood Elf Rack, Dried Fish",
        "Wood Elf Rack, Dried Meat",
        "Wood Elf Rack, Meat",
        "Wood Elf Skull and Bones",
        "Wood Elf Totem, Framed",
        "Wood Elf Totem, Skull",
        "Wood Elf Trough, Slop",
        "Wood Elf Urn, Deer",
        "Wood Elf Urn, Scratched",
        "Wood Elf Vase, Chipped",
        "Wood Elf Vase, Painted",
        "Wood Elf Vase, Swirled",
        "Wood Elf Vessel, Tiered Ceramic",
        "Wood Elf Vessel, Tiered Painted",
        "Worm Cult Candelabra, Cold-Flame",
    },
}
