ZO_CreateStringId("SI_ANTIQUITYCOMPAREKEYBIND_NAME", "Antiquity Compare Keybind")
ZO_CreateStringId("SI_ANTIQUITYCOMPAREKEYBIND_ENABLE", "Enable hold-to-compare")
ZO_CreateStringId("SI_ANTIQUITYCOMPAREKEYBIND_ENABLE_TT", "In the Antiquities Journal, equipped-item comparison tooltips appear only while the selected activation key is held.")
ZO_CreateStringId("SI_ANTIQUITYCOMPAREKEYBIND_METHOD", "Activation method")
ZO_CreateStringId("SI_ANTIQUITYCOMPAREKEYBIND_METHOD_TT", "Shift is detected directly and does not occupy an ESO keybinding slot. Choose Custom ESO keybind to assign another key in Controls.")
ZO_CreateStringId("SI_ANTIQUITYCOMPAREKEYBIND_SHIFT", "Shift (conflict-free)")
ZO_CreateStringId("SI_ANTIQUITYCOMPAREKEYBIND_CUSTOM", "Custom ESO keybind")
ZO_CreateStringId("SI_ANTIQUITYCOMPAREKEYBIND_INSTRUCTIONS", "For a custom key, select Custom ESO keybind above, then assign Show Equipped Comparison (Custom Key) under Settings > Controls > Addon Keybinds > Antiquity Compare Keybind. Do not bind Shift there; use the conflict-free Shift option instead.")
ZO_CreateStringId("SI_BINDING_NAME_ANTIQUITY_COMPARE_KEYBIND_CATEGORY", "Antiquity Compare Keybind")
ZO_CreateStringId("SI_BINDING_NAME_ANTIQUITY_COMPARE_KEYBIND_SHOW", "Show Equipped Comparison (Custom Key)")
