-- CompanionRapportData.lua
-- Companion Rapport
-- Author: Bankroll
--
-- Data format:
--   majorPositive = gold text. Large/important positive actions, usually +25 or higher.
--   lightPositive = green text. Small repeatable positives, usually +1 to +10.
--   negative      = red text. Rapport losses.
--
-- Values and notes are display-only. ESO does not expose every cooldown/reward through a public UI API.

CompanionRapport_Data = {
    ["bastian hallix"] = {
        aliases = { "bastian" },
        majorPositive = {
            { action = "Complete a personal companion quest", amount = 500, note = "Once per quest" },
            { action = "Complete a Mages Guild daily", amount = 125, note = "Daily" },
        },
        lightPositive = {
            { action = "Visit a Mages Guild hall", amount = 10, note = "Cooldown" },
            { action = "Visit Eyevea or Artaeum", amount = 10, note = "Shared cooldown" },
            { action = "Help a random encounter", amount = 10 },
            { action = "Loot a Psijic Portal", amount = 5 },
            { action = "Scry an antiquity", amount = 5 },
            { action = "Visit crafting stations", amount = 1 },
            { action = "Read a random book", amount = 1, note = "Cooldown" },
            { action = "Kill Worm Cultists", amount = 1 },
            { action = "Kill Bandits", amount = 1 },
            { action = "Kill Night Runners in Summerset", amount = 1 },
        },
        negative = {
            { action = "Any thievery or killing friendly NPCs", amount = -25 },
            { action = "Use Blade of Woe", amount = -25 },
            { action = "Pickpocket", amount = -25 },
            { action = "Steal", amount = -5 },
            { action = "Loot a Thieves Trove", amount = -5 },
            { action = "Flee from guards", amount = -1 },
            { action = "Craft provisions with cheese", amount = -1 },
        },
    },

    ["mirri elendis"] = {
        aliases = { "mirri" },
        majorPositive = {
            { action = "Complete a personal companion quest", amount = 500, note = "Once per quest" },
            { action = "Complete Ashlander daily for Numani-Rasi", amount = 125, note = "Daily" },
            { action = "Complete a Fighters Guild daily", amount = 125, note = "Daily" },
            { action = "Enter Vivec's Library with completed Vvardenfell model", amount = 75 },
        },
        lightPositive = {
            { action = "Enter a Daedric delve or public dungeon", amount = 10, note = "Cooldown" },
            { action = "Visit the Brass Fortress", amount = 10, note = "Cooldown" },
            { action = "Excavate an antiquity", amount = 5 },
            { action = "Loot a Psijic Portal", amount = 5 },
            { action = "View completed Khajiit of the Moons", amount = 5 },
            { action = "View completed Rithana-di-Renada", amount = 5 },
            { action = "View completed House of Orsimer Glories", amount = 5 },
            { action = "View completed Vault of Moawita", amount = 5 },
            { action = "Walk up to completed Vault of Moawita", amount = 5 },
            { action = "Kill a Goblin", amount = 1 },
            { action = "Kill a Snake", amount = 1, note = "Not Lamias" },
            { action = "Craft alcohol", amount = 1 },
            { action = "Read a book from a bookshelf", amount = 1 },
            { action = "Summon Daemonic Chicken pet", amount = 1 },
            { action = "Learn a new motif", note = "Value unknown" },
        },
        negative = {
            { action = "Use Blade of Woe", amount = -25 },
            { action = "Complete a Sacrament quest", amount = -25 },
            { action = "Enter Dark Brotherhood Sanctuary", amount = -10 },
            { action = "Repeated Blade of Woe during cooldown", amount = -5 },
            { action = "Collect torchbug or butterfly", amount = -1 },
            { action = "Harvest a honeybee", amount = -1 },
            { action = "Kill a friendly NPC", note = "Value unknown" },
            { action = "Use a ship", note = "Value unknown" },
        },
    },

    ["ember"] = {
        aliases = { "ember the khajiit" },
        majorPositive = {
            { action = "Complete a personal companion quest", amount = 500, note = "Once per quest" },
            { action = "Complete a Mages Guild daily", amount = 125, note = "Daily" },
            { action = "Complete a Thieves Guild heist", amount = 125, note = "Daily/cooldown" },
            { action = "Complete a High Isle delve daily", amount = 125, note = "Daily" },
            { action = "Fence a purple-quality stolen item", amount = 25, note = "Then smaller during cooldown" },
        },
        lightPositive = {
            { action = "Harvest a runestone", amount = 1 },
            { action = "Kill wolves", amount = 1 },
            { action = "Kill werewolves", amount = 1 },
            { action = "Loot a safebox or Thieves Trove", amount = 5, note = "Then +1 during cooldown" },
            { action = "Win a Tales of Tribute game", amount = 10, note = "Then +1 during cooldown" },
            { action = "Pickpocket a guard", amount = 10, note = "Then +1 during cooldown" },
            { action = "Choose Flee when stopped by a guard", amount = 10 },
            { action = "Successfully escape after fleeing", amount = 1 },
            { action = "Use Clemency after being stopped by a guard", amount = 10 },
            { action = "Enter a restricted area", amount = 1 },
            { action = "Sell a purple-quality item to a normal vendor", amount = 1 },
            { action = "Complete a Thieves Den Tip Board quest", amount = 5 },
            { action = "Use a counterfeit pardon edict", amount = 5 },
            { action = "Enter an Outlaws Refuge or Thieves Den", amount = 1 },
            { action = "Summon Big-Eared Ginger Kitten pet", amount = 1 },
        },
        negative = {
            { action = "Pay bounty to a guard", amount = -25, note = "Then -5 during cooldown" },
            { action = "Get seen stealing, pickpocketing, looting safebox, or killing innocent NPC", amount = -10 },
            { action = "Get spotted while trespassing", amount = -10 },
            { action = "Get killed by a guard", amount = -5 },
            { action = "Fish from any source", amount = -1 },
        },
    },

    ["isobel veloise"] = {
        aliases = { "isobel", "isobel velois" },
        majorPositive = {
            { action = "Complete a personal companion quest", amount = 500, note = "Once per quest" },
            { action = "Complete a Bolgrul delve daily", amount = 125, note = "Daily" },
            { action = "Complete a High Isle world boss daily", amount = 125, note = "Daily" },
            { action = "Visit an Undaunted Enclave first time", amount = 25 },
        },
        lightPositive = {
            { action = "Kill a world boss", amount = 5 },
            { action = "Kill a delve boss", amount = 5 },
            { action = "Kill a group dungeon boss", amount = 5 },
            { action = "Kill Daedra", amount = 1 },
            { action = "Kill a boss-type Daedra", amount = 5 },
            { action = "Craft sweet food", amount = 5 },
            { action = "Craft with blacksmithing", amount = 5 },
            { action = "Complete a volcanic vent", amount = 5 },
            { action = "Visit an Undaunted Enclave again", amount = 5 },
            { action = "Talk to alliance leaders", amount = 10, note = "Value varies" },
            { action = "Talk to Lyris", amount = 10 },
            { action = "Repair gear with a repair kit", amount = 1 },
            { action = "Accept a duel request", amount = 1 },
            { action = "Summon approved dog pets", amount = 1 },
        },
        negative = {
            { action = "Kill an innocent NPC", amount = -10, note = "Then -1 during cooldown" },
            { action = "Steal from container, Thieves Trove, or innocent corpse", amount = -1 },
            { action = "Enter Dark Brotherhood Sanctuary", amount = -5 },
            { action = "Enter an Outlaws Refuge", amount = -1 },
        },
    },

    ["azandar al-cybiades"] = {
        aliases = { "azandar" },
        majorPositive = {
            { action = "Complete a personal companion quest", amount = 500, note = "Once per quest" },
            { action = "Complete daily Enchanting crafting writ", amount = 125, note = "Daily" },
            { action = "Turn in Necrom delve daily", amount = 125, note = "Daily" },
        },
        lightPositive = {
            { action = "Complete master Enchanting writ", amount = 5 },
            { action = "Visit a Mundus Stone", amount = 10 },
            { action = "Destroy final mechanism in Blackwood portal", amount = 10 },
            { action = "Go to Coldharbour, Fargrave, or Brass Fortress", amount = 10 },
            { action = "Harvest a Psijic Portal", amount = 5 },
            { action = "Scry an antiquity", amount = 5 },
            { action = "Find a lead", amount = 5 },
            { action = "Activate an Ayleid Well", amount = 5 },
            { action = "Do a regular Enchanting writ", amount = 5 },
            { action = "Steal ritual object, oddity, or magical curiosity", amount = 5 },
            { action = "Find a new lorebook", amount = 5 },
            { action = "Kill mudcrabs, dreughs, chaurus, ogres, trolls, harpies, nix-oxen, or dunerippers", amount = 1 },
            { action = "Craft tea", amount = 1 },
            { action = "Respec skills at shrine", note = "Value unknown" },
        },
        negative = {
            { action = "Go to Artaeum or Eyevea", amount = -10 },
            { action = "Play a Tales of Tribute match", amount = -1 },
            { action = "Craft coffee", amount = -1 },
            { action = "Harvest mushrooms", amount = -1 },
        },
    },

    ["sharp-as-night"] = {
        aliases = { "sharp", "sharp as night" },
        majorPositive = {
            { action = "Complete a personal companion quest", amount = 500, note = "Once per quest" },
            { action = "Complete Ashlander Hunt daily", amount = 125, note = "Daily" },
            { action = "Complete Necrom world boss daily", amount = 125, note = "Daily" },
        },
        lightPositive = {
            { action = "Harvest alchemy material", amount = 1 },
            { action = "Visit zones and Hist Trees", amount = 5, note = "Cooldown" },
            { action = "Fish", amount = 1 },
            { action = "Catch trophy fish", amount = 1 },
            { action = "Repair gear", amount = 1 },
            { action = "Loot a heavy sack", amount = 5 },
            { action = "Find M'aiq the Liar", amount = 10 },
            { action = "Kill ghosts", amount = 1 },
            { action = "Dig up a treasure chest", note = "Value unknown" },
            { action = "Earn a monster trophy", amount = 10 },
        },
        negative = {
            { action = "Pay bounty to guard", amount = -10 },
            { action = "Pickpocket a beggar", amount = -5 },
            { action = "Destroy an item", amount = -5 },
            { action = "Use outfit station", amount = -1 },
            { action = "Gear breaks", note = "Value unknown" },
            { action = "Weapon enchant runs out", note = "Value unknown" },
        },
    },

    ["tanlorin"] = {
        aliases = {},
        majorPositive = {
            { action = "Complete a personal companion quest", amount = 500, note = "Once per quest" },
            { action = "Complete a Fighters Guild daily", amount = 125, note = "Daily" },
            { action = "Complete an Alchemy crafting writ", amount = 125, note = "Daily" },
            { action = "Scribe a Grimoire", amount = 25 },
        },
        lightPositive = {
            { action = "Use a Mystery Verse Scroll in Infinite Archive", amount = 10 },
            { action = "Use Persuade in NPC dialogue", amount = 10 },
            { action = "Visit a Mundus Stone", amount = 10 },
            { action = "Craft any furnishing item", amount = 5 },
            { action = "Drink wine", amount = 5 },
            { action = "Successfully lockpick a container", amount = 5 },
            { action = "Use an Ayleid Well", amount = 5 },
            { action = "Visit Alinor", amount = 5 },
            { action = "Harvest a flower", amount = 5, note = "Then +1 during cooldown" },
            { action = "Absorb a Skyshard", amount = 5, note = "Then +1 during cooldown" },
            { action = "Fill a soul gem with Soul Trap", amount = 5, note = "Then +1 during cooldown" },
            { action = "Use Antiquarian's Eye at a dig site", amount = 5 },
            { action = "Obtain a Scribing Script", amount = 5, note = "Then +1 during cooldown" },
            { action = "Interact with an animal", amount = 5, note = "Then +1 during cooldown" },
            { action = "Obtain a Vision in Infinite Archive", amount = 5 },
            { action = "Pickpocket Nobles and Merchants", amount = 1 },
            { action = "Learn a furnishing recipe", amount = 1 },
            { action = "Craft wine at a provisioning station", amount = 1 },
            { action = "Mount an Indrik", amount = 1 },
            { action = "Kill Daedra", amount = 1 },
            { action = "Kill Maormer", amount = 1 },
            { action = "Obtain a Verse in Infinite Archive", amount = 1 },
        },
        negative = {
            { action = "Murder civilians", amount = -10, note = "Then -1 during cooldown" },
            { action = "Visit Eyevea", amount = -5 },
            { action = "Visit Artaeum", amount = -5 },
            { action = "Steal children's dolls or toys", amount = -1 },
            { action = "Enter a Mages Guildhall", amount = -1 },
            { action = "Read a Mages Guild lorebook", amount = -1 },
            { action = "Loot a Psijic Portal", amount = -1 },
            { action = "Harvest Nirnroot or Crimson Nirnroot", amount = -1 },
            { action = "Kill an Indrik", amount = -1 },
            { action = "Kill a Gryphon", amount = -1 },
        },
    },

    ["zerith-var"] = {
        aliases = { "zerith var", "zerith" },
        majorPositive = {
            { action = "Complete personal companion quest", amount = 500, note = "Once per quest" },
            { action = "Complete Northern Elsweyr Defense Force daily", amount = 125, note = "Daily" },
            { action = "Complete Tales of Tribute daily", amount = 125, note = "Daily" },
            { action = "Complete a multi-part antiquity", amount = 25, note = "Reported/unconfirmed repeat" },
        },
        lightPositive = {
            { action = "Complete The Halls of Colossus prologue quest", amount = 10 },
            { action = "Unearth an antiquity", amount = 10 },
            { action = "Kill a Dragon", amount = 10, note = "Then +1 during cooldown" },
            { action = "Destroy a Dark Anchor", amount = 10 },
            { action = "Complete a Tales of Tribute match", amount = 10 },
            { action = "Consume Purifying Bloody Mara", amount = 10 },
            { action = "Heal yourself while critically injured", amount = 10 },
            { action = "Unearth an antiquity", amount = 5 },
            { action = "Loot a heavy sack", amount = 5 },
            { action = "Visit Baandari Trading Post in Malabal Tor", amount = 5 },
            { action = "Harvest from a water node", amount = 5 },
            { action = "Defeat Tho'at Replicanum in Infinite Archive", amount = 5 },
            { action = "Defeat a Cycle Boss in Infinite Archive", amount = 1 },
            { action = "Kill a Vampire", amount = 1 },
            { action = "Kill a Skeleton", amount = 1 },
            { action = "Kill dro-m'Athra/Dar-m'Athra in Moonmont", amount = 1 },
        },
        negative = {
            { action = "Gain Vampirism from Scion of the Blood Matron", amount = -50 },
            { action = "Inflict other players with Vampirism", amount = -25 },
            { action = "Visit Hollow City in Coldharbour", amount = -5 },
            { action = "Get bounty from Necromancer criminal skill", amount = -5 },
            { action = "Consume Corrupting Bloody Mara", amount = -5 },
            { action = "Sell or launder stolen items", amount = -5 },
            { action = "Fill a soul gem with Soul Trap or Oblivion's Edge", amount = -1 },
            { action = "Murder civilians", amount = -1 },
            { action = "Use Blade of Woe", amount = -1 },
        },
    },
}
