ATT_Variables = {

  name = "AlchemyTooltips",

  isInitialized = false,

  properEffectNames = {
    [1] = "Restore Health",
    [2] = "Ravage Health",
    [3] = "Restore Magicka",
    [4] = "Ravage Magicka",
    [5] = "Restore Stamina",
    [6] = "Ravage Stamina",
    [7] = "Increase Spell Resist",
    [8] = "Breach",
    [9] = "Increase Armor",
    [10] = "Fracture",
    [11] = "Increase Spell Power",
    [12] = "Cowardice",
    [13] = "Increase Weapon Power",
    [14] = "Maim",
    [15] = "Spell Critical",
    [16] = "Uncertainty",
    [17] = "Weapon Critical",
    [18] = "Enervation",
    [19] = "Unstoppable",
    [20] = "Entrapment",
    [21] = "Detection",
    [22] = "Invisible",
    [23] = "Speed",
    [24] = "Hindrance",
    [25] = "Protection",
    [26] = "Vulnerability",
    [27] = "Lingering Health",
    [28] = "Gradual Ravage Health",
    [29] = "Vitality",
    [30] = "Defile",
    [31] = "Heroism",
    [32] = "Timidity",
  },

  replaceIcons = { -- [type(potion-7,poison-30) - level - effect1 - effect2 - effect3]
    ["7-258-1-3-5"] = "AlchemyTooltips/icons/tristat.dds",
    ["7-258-3-5-31"] = "AlchemyTooltips/icons/heroism.dds",
    ["7-258-1-27-29"] = "AlchemyTooltips/icons/vitality.dds",
    ["7-258-11-15-3"] = "AlchemyTooltips/icons/spellPower.dds",
    ["7-258-13-17-5"] = "AlchemyTooltips/icons/weaponPower.dds",
    ["7-258-19-1-3"] = "AlchemyTooltips/icons/magImmovable.dds",
    ["30-258-2-28-0"] = "AlchemyTooltips/icons/metaPoison.dds",
    ["7-258-19-1-5"] = "AlchemyTooltips/icons/stamImmovable.dds",
    ["30-258-1-3-5"] = "AlchemyTooltips/icons/tristatPoison.dds",
    ["30-258-19-23-5"] = "AlchemyTooltips/icons/unstoppable_speed_stamina_poison.dds",
    ["7-258-19-21-3"] = "AlchemyTooltips/icons/detectionMagImmovable.dds",
  },

  qualityColors = {
    [1] = "|cedededWhite|r",
    [2] = "|c00d936Green|r",
    [3] = "|c0033ffBlue|r",
    [4] = "|cb300ffPurple|r",
    [5] = "|cfcdb03Gold|r",
    [6] = "|cff7b00Orange|r",
  },
}