local poukav = LibMarcusModules['Poukav']
poukav.localization = poukav.localization or {}

poukav.localization.default = {
    DATE_PATTERN = {
        label = 'YYYY/MM/DD',
        pattern = '([0-9][0-9][0-9][0-9])[/-]([0-9][0-9])[/-]([0-9][0-9])',
        format = '%04d/%02d/%02d',
        [1] = 'year', [2] = 'month', [3] = 'day'
    },
    SUS_VALUE_THREASHOLD_DESCRIPTION = 'Minimum balance (or Highest debt) before raising a sus flag',
    SUS_VALUE_THREASHOLD_LABEL = 'Minimum balance in gold',
    IGNORE_PLAYER_INACTIVITY_THREASHOLD_DESCRIPTION = 'Time without connection after which a player is ignored in the reports.',
    IGNORE_PLAYER_INACTIVITY_THREASHOLD_LABEL = 'Number of days',
    SCAN_EXPIRATION_TIME_DESCRIPTION = 'Time after which the addon will try to refresh the scanned guild listings',
    SCAN_EXPIRATION_TIME_LABEL = 'Expiration time in minutes',
    ACCOUNTING_DAY_START_HOUR_DESCRIPTION = 'Accounting day start hour',
    ACCOUNTING_DAY_START_HOUR_LABEL = 'Hour',
    ACCOUNTING_WEEK_START_DAY_DESCRIPTION = 'Accounting first day of week',
    ACCOUNTING_WEEK_START_DAY_LABEL = 'Week day',
    OUTPUT_TEXT_COLOR_DESCRIPTION = 'Color of plain text in the chat output',
    OUTPUT_TEXT_COLOR_LABEL = 'Text color',
    OUTPUT_MEMBER_TEXT_COLOR_DESCRIPTION = 'Color of member names in the chat output',
    OUTPUT_MEMBER_TEXT_COLOR_LABEL = 'Member color',
    LOCALIZATION_ENABLED_DESCRIPTION = 'When this option is activated, Poukav commands and output are localized (if current language is supported)',
    LOCALIZATION_ENABLED_LABEL = 'Localization enabled',
    NO_KIOSK_EXERNAL_SALES_RATIO_THREASHOLD_DESCRIPTION = 'Minimum value ratio of sold items to people external to the guild before considering that a guild kiosk was available. This is to avoid demotions after a week without merchant.',
    NO_KIOSK_EXERNAL_SALES_RATIO_THREASHOLD_LABEL = 'External sales percentage',
    SIMULATE_RANKING_DESCRIPTION = 'When this option is activated, the ranking command only simulates ranking and does not actually update ranks.',
    SIMULATE_RANKING_LABEL = 'Simulate ranking',
    INITIALIZING_GUILD_CATEGORY_DATA = '[Poukav] Initializing %s\'s %s data...',
    GUILD_CATEGORY_DATA_INITIALIZED = '[Poukav]%s\'s %s data initialized',
    NEED_GUILD_PARAM = 'This command requires a guild name.',
    USER_HAS_NO_LISTING = '%s has no item listed in the trading house',
    LOG_EVENT_TYPE_INVITED = '[%s] %s invited %s',
    LOG_EVENT_TYPE_PROMOTED = '[%s] %s promoted %s to %s',
    LOG_EVENT_TYPE_DEMOTED = '[%s] %s demoted %s to %s',
    LOG_EVENT_TYPE_JOINED = '[%s] %s joined the guild%s',
    LOG_EVENT_TYPE_LEFT = '[%s] %s left the guild',
    LOG_EVENT_TYPE_KICKED = '[%s] %s kicked %s from the guild',
    LOG_EVENT_TYPE_DEPOSED_ITEM = '[%s] %s deposited %i %s (+%s)',
    LOG_EVENT_TYPE_WITHDREW_ITEM = '[%s] %s withdrew %i %s (-%s)',
    LOG_EVENT_TYPE_DEPOSITED_GOLD = '[%s] %s deposited +%s',
    LOG_EVENT_TYPE_WITHDREW_GOLD = '[%s] %s withdrew -%s',
    LOG_EVENT_TYPE_EDITED_MESSAGE_OF_THE_DAY = '[%s] %s edited the message of the day',
    LOG_EVENT_TYPE_DECLINED_APPLICATION = '[%s] %s declined application from %s',
    LOG_EVENT_TYPE_ACCEPTED_APPLICATION = '[%s] %s accepted application from %s',
    LOG_EVENT_TYPE_LISTED_THE_GUILD = '[%s] %s listed the guild in the guild finder',
    LOG_EVENT_TYPE_SOLD_ITEMS = '[%s] %s sold %d %s to %s for %s (collected %s taxes)',
    MONDAY = 'Monday',
    TUESDAY = 'Tuesday',
    WEDNESDAY = 'Wednesday',
    THURSDAY = 'Thursday',
    FRIDAY = 'Friday',
    SATURDAY = 'Saturday',
    SUNDAY = 'Sunday',
    EXECUTING_POUKAV_COMMAND = 'Executing POUKAV command: %s',
    NO_COMMAND_WAS_TYPED = 'No command was typed',
    UNKNOWN_COMMAND = 'Unknown command: %s',
    HOWTO_HELP = 'Type /poukav help to get commands documentation',
    SEARCH_COMMAND_REQUIRES_SEARCH_TYPE = 'The search command requires a search type "guild" or "member"',
    UNHANDLED_EVENT_TYPE = 'Unhandled event type: %s%s%s',
    SCANNING_GUILD_STORE = 'Scanning %s guild store page %d to %d',
    OLD_DATA_SCANNING_IN_PROGRESS = 'These data are %s old, but a scanning operation is already in progress.',
    OLD_DATA_SCAN_WILL_RUN = 'These data are %s old, a new scan is running and will show updated data once completed.',
    OLD_DATA_GO_TO_TRADING_HOUSE = 'These data are %s old, go to a trading house to refresh them.',
    CANT_SCAN_NOT_AT_TRADING_HOUSE  = 'Data cannot be scanned as player is not at the trading house.',
    CANT_EXEC_COMMAND_NOT_AT_TRADING_HOUSE = 'This command cannot be executed because no data is available and the player is not at the trading house.',
    CANT_EXEC_FIRST_SCAN_IN_PROGRESS = 'This command cannot be executed because no data is available yet and a scanning operation is already in progress for another command.',
    WAIT_FOR_SCAN_TO_COMPLETE = 'No data is available yet, please wait for the scan to complete.',
    RESUMING_SCAN = 'Resuming scan...',
    SCAN_PAUSED = 'Scan paused',
    JOINED_GUILD_AFTER_LOADING_NEED_RELOAD = 'You have joined this guild after poukav has loaded, please reload the user interface (/reloadui).',
    CREATED_RANK_AFTER_LOADING_NEED_RELOAD = 'A new rank has been created since poukav has loaded, please reload the user interface (/reloadui).',
    NO_GUILD_FOUND = 'No guild found matching %s',
    FOUND_GUILD = 'Found guild: %s(%s)',
    NO_GUILD_MEMBER_FOUND = 'No guild member found matching %s',
    FOUND_GUILD_MEMBER = 'Found guild member: %s',
    COMMAND_HELP = 'help',
    COMMAND_SEARCH = 'search',
    COMMAND_SEARCH_MEMBER = 'member',
    COMMAND_SEARCH_GUILD = 'guild',
    UNKNOWN_SEARCH_TYPE = 'Unknown search type: %s',
    COMMAND_GUILD = 'guild',
    COMMAND_SALES = 'sales',
    COMMAND_PURCHASES = 'purchases',
    COMMAND_BANK = 'bank',
    COMMAND_ITEM = 'item',
    COMMAND_TOTAL = 'total',
    UNKNOWN_TOTAL_TYPE = 'Unknown total type: %s',
    COMMAND_WHOSUS = 'whosus',
    COMMAND_LISTINGS = 'listings',
    COMMAND_EMPTY_LISTINGS = 'empty_listings',
    COMMAND_RANKS = 'ranks',
    COMMAND_DONATIONS = 'donations',
    WAIT_FOR_INITIALIZATION = 'Marcus Poukav is not done initializing, please wait until all data have been fully initialized.',
    FIRST_RECORDED_DATA = 'first recorded data',
    NOW = 'now',
    FROM_TO = 'from %s to %s',
    NO_GUILD_HISTORY_FOUND = 'No guild history found for guild %s and member %s%s',
    NO_SALES_HISTORY_FOUND = 'No sales history found matching guild %s and member %s%s',
    NO_PURCHASES_HISTORY_FOUND = 'No purchases history found matching guild %s and member %s%s',
    NO_BANK_HISTORY_FOUND = 'No bank history found matching guild %s and member %s%s',
    BANK_TOTAL = '%s deposited %s, withdrew %s (%s), deposited items for %s, withdrew items for %s (%s).',
    SALES_TOTAL = '%s\'s sales total is %s, collected taxes total is %s and purchases total is %s.',
    IS_SUS_BECAUSE = '%s is sus because their balance is %s',
    NO_SUS_FOUND = 'Good news, no sus members were found ^_^',
    LISTED_ITEM = '%s listed %d %s%s for %s %s ago %s',
    EMPTY_LISTINGS_SUMMARY = 'Out of %d guild members, %d%s have products listed, %d%s don\'t and %d have not been connected for more than %d days',
    HAS_NOTHING_LISTED = '%s has nothing listed (last connected %s ago)',
    GUILD_HAD_A_MERCHANT = 'The guild had a merchant (external sales ratio: %d%% >= %d%%)',
    ADMINISTRATORS = 'Administrators:',
    PROMOTIONS = 'Promotions:',
    DEMOTIONS = 'Demotions:',
    RANK_CALCULATION_RESULT_MESSAGE = 'Out of %d guild members:\n' ..
    '[*] %d were ignored because they have critical administratives permissions.\n' ..
    '[*] %d are inactives.\n' ..
    '[*] %d need to be promoted.\n' ..
    '[*] %d need to be demoted.\n' .. 
    '[*] %d are demotables but have already been demoted.\n' .. 
    '[*] %d do not need any change in their rank.',
    RANK_SHOULD_CHANGE = '%s should be %s from %s to %s (%s sales + %s purchases + %s donations = %s)',
    CHANGING_RANK = '%s is being %s from %s to %s (%s sales + %s purchases + %s donations = %s)',
    PROMOTED = 'promoted',
    DEMOTED = 'demoted',
    CANT_RANK_IT_LOOKS_LIKE_NO_MERCHANT_WAS_HIRED = 'It looks like the guild had no kiosk %s (external sales ratio %d%%).\nRanks cannot be computed.',
    FOUND_NO_RANK_TO_UPDATE = 'Found no member that needs to be promoted/demoted',
    NO_DONATION_SET = 'No donation set for %s.\nYou can set a donation by filling the three dedicated fields in this guild\'s settings',
    MEMBER_LATE_ON_DONATION = '%s %s%s (%s) is late on their donation, full donations %d/%d, total gold deposits %s, sales %s.',
    DONATIONS_SUMMARY = 'Out of %d active members, %d are up to date with their donation and %d are not',
    MISSING_AMOUNT = 'Missing amount: %s',
    COMPUTING_MEMBER_INFO = 'Computing members info...',
    READING_SALES_DATA  = 'Loading sales data...',
    READING_BANK_DATA  = 'Loading bank data...',
    HELP_REQUIRES_COMMAND_NAME = 'Use help command with a <keyword> parameter to get help about the associated feature.',
    HELP_USAGE_FORMAT = 'Usage: /poukav %s %s',
    HELP_PARAM_ONE_OF = 'Where %s is one of:',
    HELP_COMMAND_DESCRIPTION_LINE = '* "%s", %s.',
    COMMAND_SEARCH_DESCRIPTION = 'for searching guild or member functionality',
    COMMAND_GUILD_DESCRIPTION = 'for searching into guild history',
    COMMAND_BANK_DESCRIPTION = 'for searching into bank history',
    COMMAND_SALES_DESCRIPTION = 'for searching into sales history',
    COMMAND_TOTAL_DESCRIPTION = 'to get balance of gold deposits/withdrawals or sales totals',
    COMMAND_LISTINGS_DESCRIPTION = 'to get a member product listings',
    COMMAND_EMPTY_LISTINGS_DESCRIPTION = 'list of users without product listed',
    COMMAND_WHOSUS_DESCRIPTION = 'list of members with a suspuscious balance',
    TIMEFRAME_PARAM = 'timeframe',
    TIMEFRAME_PARAM_DESCRIPTION = 'how to define a timeframe with the timeframe parameter',
    TIMEFRAME_PARAM_LONG_DESCRIPTION = 'A timeframe param consist of a start expression and optionally an end expression (in which case they\'re separated by an arrow =>). The expressions consisting of a time unit (D for day, W for week, M for month) and optionally a negative offset (D-1 for yesterday, W-2 for two weeks ago...etc)',
    HELP_COMMAND_HELP_EXAMPLE = 'Example: /poukav help search',
    SEARCH_HELP_OUTPUT = 'Searches for guild or member given a name or partial name.\n' ..
    'Usage: /poukav %s <kind> <search string>\n' ..
    'Where <kind> is either "%s" or "%s".\n' ..
    'Example: /poukav %s %s crew\n' ..
    'Returns:\n' ..
    'PoukavCrew1 (666666)\n' ..
    'PoukavCrew2 (666667)\n\n' ..
    'Note that when searching for a member, the guild name must also be specified.\n' ..
    'Example: /poukav %s %s crew1 billy\n' ..
    'Returns:\n' ..
    'Found guild: PoukavCrew1 (666666)\n' ..
    '@PoukavBilly\n',
}

poukav.localization.localized = poukav.localization.localized or {}

for k, v in pairs(poukav.localization.default) do
    if poukav.localization.localized[k] == nil then
        poukav.localization.localized[k] = v
    end
end
