local poukav = LibMarcusModules['Poukav']
poukav.localization = poukav.localization or {}

poukav.localization.localized = {
    DATE_PATTERN = {
        label = 'JJ/MM/AAAA',
        pattern = '([0-9][0-9])[/-]([0-9][0-9])[/-]([0-9][0-9][0-9][0-9])',
        format = '%02d/%02d/%04d',
        [1] = 'day', [2] = 'month', [3] = 'year'
    },
    SUS_VALUE_THREASHOLD_DESCRIPTION = 'Solde minimum (ou dette maximum) avant alerte',
    SUS_VALUE_THREASHOLD_LABEL = 'Solde minimum en or',
    IGNORE_PLAYER_INACTIVITY_THREASHOLD_DESCRIPTION = 'Les joueurs non connectés depuis au moins ce nombre de jours sont ignorés',
    IGNORE_PLAYER_INACTIVITY_THREASHOLD_LABEL = 'Nombre de jours',
    SCAN_EXPIRATION_TIME_DESCRIPTION = 'Temps en minutes après lequel cet addon va tenter de rafraichir les scans du contenu de la boutique.',
    SCAN_EXPIRATION_TIME_LABEL = 'Temps d\'expiration en minutes',
    ACCOUNTING_DAY_START_HOUR_DESCRIPTION = 'Heure du début de journée comptable',
    ACCOUNTING_DAY_START_HOUR_LABEL = 'Heure',
    ACCOUNTING_WEEK_START_DAY_DESCRIPTION = '1er jour de la semaine comptable',
    ACCOUNTING_WEEK_START_DAY_LABEL = 'Jour de la semaine',
    OUTPUT_TEXT_COLOR_DESCRIPTION = 'Couleur normale du texte dans la sortie du chat',
    OUTPUT_TEXT_COLOR_LABEL = 'Couleur du texte',
    OUTPUT_MEMBER_TEXT_COLOR_DESCRIPTION = 'Couleur des noms de membres dans la sortie du chat',
    OUTPUT_MEMBER_TEXT_COLOR_LABEL = 'Couleur des membres',
    LOCALIZATION_ENABLED_DESCRIPTION = 'Quand cette option est activée, les commandes et la sortie Poukav sont localisées (si la localisation pour le langage en cours est disponible)',
    LOCALIZATION_ENABLED_LABEL = 'Localisation activée',
    NO_KIOSK_EXERNAL_SALES_RATIO_THREASHOLD_DESCRIPTION = 'Ratio minimum de ventes à des personnes en dehors de la guilde avant de considérer qu\'un marchand de guilde était disponible. Ceci est pour éviter de rétrograder par erreur des membres après une semaine sans marchand.',
    NO_KIOSK_EXERNAL_SALES_RATIO_THREASHOLD_LABEL = 'Pourcentage de ventes externes',
    SIMULATE_RANKING_DESCRIPTION = 'Quand cette option est activée, la commande de rangs ne fait que simuler les mises à jour et ne change pas les rangs des membres.',
    SIMULATE_RANKING_LABEL = 'Simuler la mise à jour des rangs',
    INITIALIZING_GUILD_CATEGORY_DATA = '[Poukav] Initialisation des données %s / %s...',
    GUILD_CATEGORY_DATA_INITIALIZED = '[Poukav] Données %s / %s chargées',
    NEED_GUILD_PARAM = 'Cette commande nécessite un nom de guilde.',
    USER_HAS_NO_LISTING = "%s n'a aucun produit listé dans la boutique de guilde.",
    LOG_EVENT_TYPE_INVITED = '[%s] %s a invité %s.',
    LOG_EVENT_TYPE_PROMOTED = '[%s] %s a promu %s au rang de %s.',
    LOG_EVENT_TYPE_DEMOTED = '[%s] %s a retrogradé %s au rang de %s.',
    LOG_EVENT_TYPE_JOINED = '[%s] %s a rejoint la guilde %s.',
    LOG_EVENT_TYPE_LEFT = '[%s] %s a quitté la guilde.',
    LOG_EVENT_TYPE_KICKED = '[%s] %s a viré %s de la guilde.',
    LOG_EVENT_TYPE_DEPOSED_ITEM = '[%s] %s a déposé %i %s (+%s).',
    LOG_EVENT_TYPE_WITHDREW_ITEM = '[%s] %s a retiré %i %s (-%s).',
    LOG_EVENT_TYPE_DEPOSITED_GOLD = '[%s] %s a déposé +%s.',
    LOG_EVENT_TYPE_WITHDREW_GOLD = '[%s] %s a retiré -%s.',
    LOG_EVENT_TYPE_EDITED_MESSAGE_OF_THE_DAY = '[%s] %s a édité le message du jour.',
    LOG_EVENT_TYPE_DECLINED_APPLICATION = '[%s] %s a refusé la candidature de %s.',
    LOG_EVENT_TYPE_ACCEPTED_APPLICATION = '[%s] %s a accepté la candidature de %s.',
    LOG_EVENT_TYPE_LISTED_THE_GUILD = '[%s] %s a listé la guilde dans la recherche de guilde.',
    LOG_EVENT_TYPE_SOLD_ITEMS = '[%s] %s a vendu %d %s a %s pour %s (collectés %s taxes)',
    MONDAY = 'Lundi',
    TUESDAY = 'Mardi',
    WEDNESDAY = 'Mercredi',
    THURSDAY = 'Jeudi',
    FRIDAY = 'Vendredi',
    SATURDAY = 'Samedi',
    SUNDAY = 'Dimanche',
    EXECUTING_POUKAV_COMMAND = 'Execution de la commande POUKAV: %s',
    NO_COMMAND_WAS_TYPED = 'Aucune commande n\'a été saisie.',
    UNKNOWN_COMMAND = 'Commande inconnue: %s',
    HOWTO_HELP = 'Tapez /poukav aide pour avoir la documentation des commandes.',
    SEARCH_COMMAND_REQUIRES_SEARCH_TYPE = 'La commande de recherche nécessite un type de recherche "guilde" ou "membre"',
    UNHANDLED_EVENT_TYPE = 'Type d\'évènement non géré: %s\n%s',
    SCANNING_GUILD_STORE = 'Scan en cours de la boutique de la guilde %s, page %d à %d',
    OLD_DATA_SCANNING_IN_PROGRESS = 'Ces données sont vieilles de %s, mais un scan est déjà en cours.',
    OLD_DATA_SCAN_WILL_RUN = 'Ces données sont vieilles de %s, un nouveau scan est lancé et les données à jour seront affichées à la fin du scan.',
    OLD_DATA_GO_TO_TRADING_HOUSE = 'Ces données sont vieilles de %s, allez à votre boutique de guilde pour raffraichir.',
    CANT_SCAN_NOT_AT_TRADING_HOUSE  = 'Les données ne peuvent être scannées car le joueur n\'est pas à sa boutique de guilde.',
    CANT_EXEC_COMMAND_NOT_AT_TRADING_HOUSE = 'Cette commande ne peut être exécutée car aucune donnée n\'a été chargée et le joueur n\'est pas à sa boutique de guilde.',
    CANT_EXEC_FIRST_SCAN_IN_PROGRESS = 'Cette commande ne peut être exécutée car aucune donnée n\'a été chargée et un scan est déjà en cours pour une autre commande.',
    WAIT_FOR_SCAN_TO_COMPLETE = 'Aucune données n\'est encore disponible, veuillez attendre la fin du scan.',
    RESUMING_SCAN = 'Reprise du scan...',
    SCAN_PAUSED = 'Scan en pause',
    JOINED_GUILD_AFTER_LOADING_NEED_RELOAD = 'Vous avez rejoint cette guilde après le chargement de Poukav, veuillez recharger l\'interface utilisateur (/reloadui).',
    CREATED_RANK_AFTER_LOADING_NEED_RELOAD = 'Un nouveau rang a été créé depuis le chargement de poukav, veuillez recharger l\'interface utilisateur (/reloadui).',
    NO_GUILD_FOUND = 'Aucune guilde trouvée correspondant à %s',
    FOUND_GUILD = 'Trouvée guilde: %s(%s)',
    NO_GUILD_MEMBER_FOUND = 'Aucun membre de guilde trouvé correspondant à %s',
    FOUND_GUILD_MEMBER = 'Trouvé membre de guilde: %s',
    COMMAND_HELP = 'aide',
    COMMAND_SEARCH = 'cherche',
    COMMAND_SEARCH_MEMBER = 'membre',
    COMMAND_SEARCH_GUILD = 'guilde',
    UNKNOWN_SEARCH_TYPE = 'Type de recherche inconnu: %s',
    COMMAND_GUILD = 'guilde',
    COMMAND_SALES = 'ventes',
    COMMAND_PURCHASES = 'achats',
    COMMAND_BANK = 'banque',
    COMMAND_ITEM = 'item',
    COMMAND_TOTAL = 'total',
    UNKNOWN_TOTAL_TYPE = 'Type de total inconnu: %s',
    COMMAND_WHOSUS = 'quilouche',
    COMMAND_LISTINGS = 'articles',
    COMMAND_EMPTY_LISTINGS = 'zero_articles',
    COMMAND_RANKS = 'rangs',
    COMMAND_DONATIONS = 'donations',
    WAIT_FOR_INITIALIZATION = 'Marcus Poukav n\'a pas fini de s\'initialiser, veuillez attendre la fin du chargement des données.',
    FIRST_RECORDED_DATA = 'la première donnée enregistrée',
    NOW = 'maintenant',
    FROM_TO = 'de %s à %s',
    NO_GUILD_HISTORY_FOUND = 'Pas d\'historique de guilde trouvé pour la guilde %s et le membre %s%s',
    NO_SALES_HISTORY_FOUND = 'Pas d\'historique de ventes trouvé pour la guilde %s et le membre %s%s',
    NO_PURCHASES_HISTORY_FOUND = 'Pas d\'historique d\'achats trouvé pour la guilde %s et le membre %s%s',
    NO_BANK_HISTORY_FOUND = 'Pas d\'historique bancaire trouvé pour la guilde %s et le membre %s%s',
    BANK_TOTAL = '%s a déposé %s, a retiré %s (%s), a déposé des items pour %s, a retiré des items pour %s (%s).',
    SALES_TOTAL = '%s a vendu pour un total de %s, a rapporté en taxes %s et fait %s d\'achats.',
    IS_SUS_BECAUSE = '%s est louche car son solde est de %s',
    NO_SUS_FOUND = 'Bonne nouvelle, aucun membre louche n\'a été trouvé ^_^',
    LISTED_ITEM = '%s a mis en vente %d %s%s pour %s il y a %s %s',
    EMPTY_LISTINGS_SUMMARY = 'Sur %d membres de guilde, %d%s ont des articles en vente, %d%s n\'en ont pas et %d n\'ont pa été connectés depuis plus de %d jours',
    HAS_NOTHING_LISTED = '%s n\'a aucun article en vente (connecté il y a %s)',
    GUILD_HAD_A_MERCHANT = 'La guilde avait un marchand (pourcentage de ventes externes: %d%% >= %d%%)',
    ADMINISTRATORS = 'Administrateurs:',
    PROMOTIONS = 'Promotions:',
    DEMOTIONS = 'Rétrogradations:',
    RANK_CALCULATION_RESULT_MESSAGE = 'Sur %d membres de guilde:\n' ..
    '[*] %d ont été ignorés parce qu\'ils ont des droits administratifs critiques.\n' ..
    '[*] %d sont inactifs.\n' ..
    '[*] %d doivent être promus.\n' ..
    '[*] %d doivent être rétrogradés.\n' .. 
    '[*] %d sont rétrogradables mais l\'ont déjà été.\n' .. 
    '[*] %d n\'ont pas besoin de changer de rang.',
    RANK_SHOULD_CHANGE = '%s devrait être %s de %s à %s (%s ventes + %s achats + %s donations = %s)',
    CHANGING_RANK = '%s est %s de %s à %s (%s ventes + %s achats + %s donations = %s)',
    PROMOTED = 'promu(e)',
    DEMOTED = 'rétrogradé(e)',
    CANT_RANK_IT_LOOKS_LIKE_NO_MERCHANT_WAS_HIRED = 'Il semble que la guilde n\'avait pas de marchand %s (ratio de ventes externes %d%%).\nLes rangs ne peuvent pas être calculés.',
    FOUND_NO_RANK_TO_UPDATE = 'Aucun membre nécessitant un changement de rang n\'a été trouvé',
    NO_DONATION_SET = 'Aucune donation n\'est configurée pour %s.\nVous pouvez définir une donation en remplissant les trois champs dédiés dans les réglages de cette guilde',
    MEMBER_LATE_ON_DONATION = '%s %s%s (%s) est en retard sur ses donations, donations complètes %d/%d, total dépôts d\'or %s, ventes %s.',
    DONATIONS_SUMMARY = 'Sur %d membres actifs, %d sont à jour sur leur donations et %d ne le sont pas.',
    MISSING_AMOUNT = 'Montant manquant: %s',
    COMPUTING_MEMBER_INFO = 'Calcul des informations des membres...',
    READING_SALES_DATA  = 'Chargement des données de ventes...',
    READING_BANK_DATA  = 'Chargement des données bancaires...',
    HELP_REQUIRES_COMMAND_NAME = 'L\'aide de Poukav nécessite un nom de commande.',
    HELP_USAGE_FORMAT = 'Emploi: /poukav %s %s',
    HELP_PARAM_ONE_OF = 'Où %s est au choix:',
    HELP_COMMAND_DESCRIPTION_LINE = '* "%s", %s.',
    COMMAND_SEARCH_DESCRIPTION = 'pour avoir de l\'aide sur comment chercher une guilde ou un membre',
    COMMAND_GUILD_DESCRIPTION = 'pour avoir de l\'aide sur la recherche dans l\'historique de guilde',
    COMMAND_BANK_DESCRIPTION = 'pour avoir de l\'aide sur la recherche dans l\'historique bancaire',
    COMMAND_SALES_DESCRIPTION = 'pour avoir de l\'aide sur la recherche dans l\'historique de vente',
    COMMAND_TOTAL_DESCRIPTION = 'solde des dépots/retraits ou total des ventes',
    COMMAND_LISTINGS_DESCRIPTION = 'voir les articles listés par les membres de la guilde',
    COMMAND_EMPTY_LISTINGS_DESCRIPTION = 'voir les membres de guilde sans articles en vente',
    COMMAND_WHOSUS_DESCRIPTION = 'liste des membres avec un solde louche',
    TIMEFRAME_PARAM = 'période',
    TIMEFRAME_PARAM_DESCRIPTION = 'comment définir une période avec le paramètre de période',
    TIMEFRAME_PARAM_LONG_DESCRIPTION = 'Un paramètre de période est composé d\'une expression de début et optionellement une expression de fin,\nauquel cas elles sont séparées par une flèche "=>".\nLes expressions elles mêmes sont composées d\'une unité de temps (D pour jour, W pour semaine, M pour mois)\net optionellement d\'un décalage négatif (D-1 pour hier, W-2 la semaine d\'avant la semaine dernière...etc)',
    HELP_COMMAND_HELP_EXAMPLE = 'Exemple: /poukav aide cherche',
    SEARCH_HELP_OUTPUT = 'Cherche une guilde ou un membre à partir d\'un nom ou partie d\'un nom.\n' ..
    'Emploi: /poukav %s <type> <chaine de recherche>\n' ..
    'Où <type> est soit "%s" soit "%s".\n' ..
    'Exemple: /poukav %s %s crew\n' ..
    'Retourne:\n' ..
    'PoukavCrew1 (666666)\n' ..
    'PoukavCrew2 (666667)\n\n' ..
    'Notez que pour chercher un membre, un nom de guilde doit aussi être spécifié.\n' ..
    'Example: /poukav %s %s crew1 billy\n' ..
    'Retourne:\n' ..
    'Guilde trouvée: PoukavCrew1 (666666)\n' ..
    '@PoukavBilly\n',
}
