ThiefTools_localization_strings = ThiefTools_localization_strings  or {}

ThiefTools_localization_strings["en"] = {
    -- General
    TT_INITIALIZE = "Thief Tools Initialized...",
    
    TT_NOT_THIEF = "This character is not a thief:",
    TT_NOT_THIEF_TT = "Turn off Thief Tools Status Bar for this character.",
    
    -- Settings Panel
    TT_AW_NAME = "Apply these settings account-wide:",
    TT_AW_NAME_TT = "If ON, the settings in this section apply account-wide instead of just to this one character.",
    
    -- Submenu - Status Bar Display
    TT_STATUSBAR_TITLE = "Status Bar Display",
    TT_STATUSBAR_AWTITLE = "Status Bar Display (AW)",
    TT_BAR_FIELDS_NM = "Fields",
    TT_BAR_FIELDS = "Which items to display on Thief Status Bar.",
	TT_BAR_ASSASSIN_NAME = "Show Kill innocents mode (dynamic)",
	TT_BAR_ASSASSIN = "The option to show that killing of innocents is enabled.",
	TT_BAR_SNEAKSTEAL_NAME = "Show auto-steal in sneak mode (dynamic)",
	TT_BAR_SNEAKSTEAL = "The option to show that auto-stealing containers while in sneak is enabled.",
    TT_BAR_GOLD_VALUE_NAME = "Gold value",
    TT_BAR_GOLD_VALUE = "Display the total gold value of stolen fence-able items",
    TT_BAR_SELLS_NAME = "Show sells (to the fences) remaining",
    TT_BAR_SELLS = "Display the total remaining times you can fence items",
    TT_BAR_LAUNDERS_NAME = "Show launders (to the fences) remaining",
    TT_BAR_LAUNDERS = "Display the total remaining times you can launder items",
    TT_BAR_FENCE_RESET_NAME = "Show the Fence Reset Clock",
    TT_BAR_FENCE_RESET = "Display the time that you have left until the Fence resets.",
    TT_BAR_BOUNTY_CLOCK_NM = "Show the Bounty Reset Clock",
    TT_BAR_BOUNTY_CLOCK = "(\"Dynamic Bounty\" will hide this if you have no bounty)",
    TT_BAR_BOUNTY_NAME = "Show Bounty",
    TT_BAR_BOUNTY = "(\"Dynamic Bounty\" will hide this if you have no bounty)",
    TT_BAR_CLEMENCY_RESET_NAME = "Show the Clemency Reset Clock",
    TT_BAR_CLEMENCY_RESET = "Display the time that you have left until the Clemency resets.",
    TT_BAR_AVE_VALUE_NM = "Show average value",
    TT_BAR_AVE_VALUE = "Display the average value of an item (i.e., ratio of value to item count)",
    TT_BAR_EST_PROFIT_NM = "Show estimated daily profit",
    TT_BAR_EST_PROFIT = "Show the estimated daily haul based on remaining fence sells and the average stolen item value",
    TT_BAR_AVE_QUAL_NM = "Show average quality",
    TT_BAR_AVE_QUAL = "Display the average quality of item",
    TT_BAR_QUAL_GRAPH_NM = "Show the quality graph",
    TT_BAR_QUAL_GRAPH = "Display the graph of item quality to percentage held",
    
    -- Display Section
    TT_METER_NAME = "Bounty Meter",
    TT_METER_DESC = "Control the visibility of the default bounty meter.",
    TT_METER = "When the default Bounty Meter is displayed.",
    TT_METER_HIDE_NAME = "Hide Bounty Meter",
    TT_METER_HIDE = "If this is checked the default Bounty Meter will be hidden",
    TT_METER_DYNAMIC_NM = "Dynamic bounty/timer",
    TT_METER_DYNAMIC = "Show and hide the bounty and bounty timer automatically, when there is bounty",
    
    
    -- Submenu - Stolen Item Filters
    TT_FILTERS_NAME = "Filters",
    TT_FILTERS_AWNAME = "Filters (AW)",
    TT_FILTERS = "Filtering categories of items to count towards your total fence/launder counts and total gold value.",
    TT_CHOICES_FENCE = "Fence",
    TT_CHOICES_LAUNDER = "Launder",
    TT_CHOICES_IGNORE = "Ignore",
    TT_CHOICES_JUNK = "Junk",
    TT_CHOICES_CUSTOM = "Custom",
    TT_QUAL_NORMAL = "Normal",
    TT_QUAL_FINE = "Fine",
    TT_QUAL_SUPERIOR = "Superior",
    TT_QUAL_EPIC = "Epic",
    TT_QUAL_LEGENDARY = "Legendary",
    
    -- Filters Drop Down
    TT_OPTIONS_NAME= "Options",
    TT_OPTIONS = "General options.",

	TT_NOJUNK_NAME = "Don't count junk",
    TT_NOJUNK = "If a stolen item is marked as junk, it won't be counted",
    TT_IGNORE_SCALE_NAME = "Ignore items of value less than...",
    TT_IGNORE_SCALE = "Ignore trash",
	TT_JUNK_INSTEAD_NAME = "Auto-junk instead of ignore value less than...",
	TT_JUNK_INSTEAD = "Auto-junk trash instead",
	TT_NEVER_JUNK = "Never auto-junk quality equal to or better than...",
	TT_NEVER_JUNK_NAME = "Never auto-junk quality",
	TT_AUTO_UNJUNK = "Move laundered items out of junk",
	TT_AUTO_UNJUNK_TT = "You spent money to launder it. You probably don't want to accidentally throw it away.",
    
    TT_FILTERS_HEADER = "Stolen Item Filters",
    TT_FILTER_DESC = "Choose if you want stolen items counted as fence-able, launder-able, or simply ignored. Categories of items not listed here are set as fence-able (as long as they are at least the minimum value).",
    TT_PROV_RECIPE_NAME = "Food & Drink Recipes",
    TT_PROV_RECIPE = "If a stolen item is a provisioning recipe, count it with recipes and choose what to do with it.",
    TT_FURN_RECIPE_NAME = "Furnishing Recipes",
    TT_FURN_RECIPE = "If a stolen item is a furnishing recipe, count it with recipes and choose what to do with it.",
    TT_MOTIF_NAME = "Motifs",
    TT_MOTIF = "If a stolen item is a motif, count it separately and choose what to do with it.",	
    TT_STYLE_NAME = "Styles",
    TT_STYLE = "If a stolen item is a style material, choose what to do with it.",
    TT_TRAIT_NAME = "Traits",
    TT_TRAIT = "If a stolen item is a trait material, choose what to do with it.",
    TT_FURNITURE_NAME = "Furniture",
    TT_FURNITURE = "If a stolen item is a piece of furniture, choose what to do with it.",
    TT_GEAR_NAME = "Gear",
    TT_GEAR = "If a stolen item is an armor or weapon, choose what to do with it.",
    TT_LOCKPICK_NAME = "Lockpicks",
    TT_LOCKPICK = "If a stolen item is a lockpick, choose what to do with it.",
    TT_SOULGEM_NAME = "Soul gems",
    TT_SOULGEM = "If a stolen item is a soul gem, choose what to do with it.",
    TT_INGREDIENT_NAME = "Ingredients",
    TT_INGREDIENT = "If a stolen item is an ingredient, choose what to do with it.",
    TT_ALCH_SOLVENTS_NM = "Alchemical solvents",
    TT_ALCH_REAGENTS_NM = "Alchemical reagents",
    TT_ALCH_REAGENTS = "Alchemical reagents (herbs, mushrooms, etc.)",
	TT_JEWELRY = "Stolen Jewelry (Rings and Necklaces)",
	TT_JEWELRY_NM = "Jewelry (Rings and Necklaces)",
    
    -- Display Section
    TT_CHOICES_LEFT = "Left",
    TT_CHOICES_RIGHT = "Right",
    TT_CHOICES_CENTER = "Center",
    
    TT_DISPLAY_NAME = "Display (AW)",
    TT_DISPLAY = "How the Thief Status Bar is displayed. (Settings apply to all characters)",
    
    TT_SECTION_LOC_NM = "Location Settings",
    TT_SECTION_LOC = "Options that change where the status bar is displayed.",
    TT_LOCKUI_NAME = "Lock UI Position",
    TT_LOCKUI = "If checked, the Thief Tools UI will be locked in place.",
    TT_AUTO_LOCK_NAME = "Autolock",
    TT_AUTO_LOCK = "This will automatically lock the window when you release it after moving.",
    
    TT_SECTION_DISP_NM = "Display Settings",
    TT_SECTION_DISP = "Options that change how the status bar is displayed.",
    TT_SCALE_NAME = "Scale",
    TT_BACKGROUND_NAME = "Show background",
    TT_BACKGROUND = "If this is unchecked, the background will not be displayed",
    TT_HIDE_IN_MENUS_NAME = "Hide in menus",
    TT_HIDE_IN_MENUS = "When set, the bar will be hidden when in menus.",
    TT_HIDE_IN_IA_NAME = "Hide in Infinite Archive",
    TT_HIDE_IN_IA = "When set, the bar will be hidden when in the Infinite Archive.",
    TT_HIDE_IN_DUNG_NAME = "Hide in group dungeons.",
    TT_HIDE_IN_DUNG = "When set, the bar will be hidden when in normal and veteran group dungeons.",
    TT_HIDE_IN_TRIAL_NAME = "Hide in trials",
    TT_HIDE_IN_TRIAL = "When set, the bar will be hidden when in trials.",
    TT_HIDE_IN_ARENA_NAME = "Hide in arenas",
    TT_HIDE_IN_ARENA = "When set, the bar will be hidden when in arenas.",
    TT_HIDE_IN_PUBDGN_NAME = "Hide in delves",
    TT_HIDE_IN_PUBDGN = "When set, the bar will be hidden when in delves and public dungeons.",

    -- Warning annoucements and settings
    TT_WARNINGS_NAME = "Warning Announcements",
    TT_WARNINGS_AWNAME = "Warning Announcements (AW)",
    TT_WARNINGS = "Options to display warnings. (Setting them to zero turns them off.)",
    
    TT_FENCESLOTS_NAME = "Fence Quota warning",
    TT_FENCESLOTS = "Warn (in chat) that you have stolen enough to meet todays Fence quota.",
    TT_FENCE_SLOTS_LEFT="Estimated Fence sells left: ",

    TT_SLOTSLEFT_NAME = "Backpack free space warning",
    TT_SLOTSLEFT = "Put warning in chat when you have this number (or less) of free slots left in your backpack.",
    TT_FREE_SLOTS_LEFT ="Free slots left: ",
    
    
    --Text for command list on chat (Help)
    TT_CHAT_THIEFTOOLS_COMMANDS = "Thief Tools commands:",
    TT_CHAT_THIEFTOOLS_LISTCOMMANDS = "List all chat commands",
    TT_CHAT_CMD_TOGGLE = "Toggle show Thief Status bar",
    TT_CHAT_CMD_LOCK_BAR_POSITION = "Toggle lock bar position",
    TT_CHAT_CMD_METER = "Toggle hide bounty meter",
    TT_CHAT_CMD_FENCETIME = "Report time until fence reset",
    TT_CHAT_CMD_FENCE_ACK = "Fence will reset in ",
    TT_CHAT_CMD_RECALC = "Rescan backpack stolen items for status bar",
    TT_CHAT_CMD_RECALC_ACK = "Rescanning backpack for stolen items ",
    TT_CHAT_CMD_COUNTS = "Show current categorized counts of stolen items",
    TT_CHAT_CMD_SAFE = "Toggle attack innocents mode",
    TT_CHAT_CMD_AUTOSTEAL = "Toggle automatic stealing while sneaking mode",
    TT_CHAT_CMD_TTFAS = "Toggle filtered stealing while sneaking mode",
    TT_CHAT_CMD_AUTOJUNK = "Toggle automatic junking of loot mode",
    TT_CHAT_CMD_START = "Turn on ThiefTools",
    TT_CHAT_CMD_STOP = "Temporarily turn off ThiefTools",
    TT_CHAT_NOT_RUNNING = "ThiefTools is not currently running",
    TT_CHAT_TTFAS_NOT_AVAIL = "ThiefTools Filtered AutoSteal is not currently available.",

    -- display for /tt.counts
    TT_STATS_RECIPES = "Recipes stolen: ",
    TT_STATS_MOTIFS = "Motifs stolen: ",
    TT_STATS_FURNITURE = "Furniture stolen: ",
    TT_STATS_OTHER = "Other stolen: ",
    TT_STATS_FENCE = "Fence Count: ",
    TT_STATS_LAUNDER = "Launder Count: ",

    TT_MSG_LOCKED = "ThiefTools Status Bar Locked",
    TT_MSG_UNLOCKED = "ThiefTools Status Bar Unlocked",
    
    -- Text for messages
    TT_SAFE_INNOCENTS = "Attacking innocents is prevented",
    TT_UNSAFE_INNOCENTS = "Attacking innocents is allowed",
    TT_AUTOSTEAL_ON = "Automatically stealing while sneaking is ON",
    TT_AUTOSTEAL_OFF = "Automatically stealing while sneaking is OFF",
	TT_TTFAS_ON = "TT Filtered AutoStealing is ON",
	TT_TTFAS_OFF = "TT Filtered AutoStealing is OFF",
	TT_ANNOUNCE_BE_CAREFUL = "Be Careful!",
    TT_AUTOJUNK_ON="Auto-junking stolen items is turned on",
    TT_AUTOJUNK_OFF="Auto-junking stolen items is turned off",
    TT_STOPPING = "Stopping ThiefTools",
    TT_ALREADY_STOPPED = "ThiefTools is already stopped",
    TT_STARTING = "Starting ThiefTools",
    TT_ALREADY_RUNNING = "ThiefTools is already running",
	
	-- Text for key binds
	TT_BINDING_TOGGLE="Toggle Display Bar",
	TT_BINDING_KILL_TOGGLE="Toggle Kill Innocents",
	TT_BINDING_AUTOSTEAL_TOGGLE="Toggle Auto-Steal",
	TT_BINDING_AUTOJUNK_TOGGLE="Toggle Auto-Junk, stolen",
	TT_BINDING_LOCK_TOGGLE="Toggle Position Lock",
	TT_BINDING_METER_TOGGLE="Toggle Bounty Meter",
}
